### ISSUE TITLE
Allow configuring http client timeout

### ISSUE THREAD

**Issue by or-shachar** [CircleCI-Public/circleci-cli#1012]
## What problem does this feature solve?:
- Our CI validates the circleci configuration size by running `circleci config process / validate` commands
- Ocassianally the `circleci` fails to execute due to timeout.
- Looking at the code it seems like the http client is configured to 10s timeout ([here](https://github.com/CircleCI-Public/circleci-cli/blob/v0.1.29041/api/rest/client.go#L43))
- I think this should be configurable by either env variable or global flag

## Provide an example:
```
export HTTP_TIMEOUT=30s
circleci config validate config.yml
```

or 
```
circleci --http_timeout 30s config validate config.yml
```

**Comment by loderunner** [comment]
Love the idea! This should be simple to merge. I think the feature has a few more requirements:

1. I don't see where the global flag `--http_timeout` is setup? Did you do that part? Also, from the user's point of view, I don't think it matters that this is HTTP in the flag. Let's just call it `--timeout` and add the HTTP part to the inline help.
2. `HTTP_TIMEOUT` seems like too generic a term. Can we add a prefix to "namespace" the environment variable? `CIRCLECI_CLI_TIMEOUT=30s` should do fine.
3. There is another HTTP client in the CLI, used for exchanging with the GraphQL API (mostly for Orbs). Can we make sure the timeout is applied to both clients? ([source](https://github.com/CircleCI-Public/circleci-cli/blob/b3874b3cb2cca29633142a24294d0051e7ed3d1d/settings/settings.go#L289-L292))

Finally, I'd like to see at least one test in there. You can add an integration test to [`config/commands_test.go`](https://github.com/CircleCI-Public/circleci-cli/blob/fde1bce50a3e19e9049a05de45f52a48d27c42e2/config/commands_test.go#L61), creating a new mock server with `httptest.NewServer` that takes longer time to respond than the timeout.

Let me know if any of this is unclear, I'll be glad to help.

**Comment by abdelDriowya** [comment]
@or-shachar cli released you can define http timeout now
