### ISSUE TITLE
CircleCI CLI policy test command missing timestamp in JUnit output

### ISSUE THREAD

**Issue by madrob** [CircleCI-Public/circleci-cli#1048]
## Meta:

**CircleCI CLI Version:**
0.1.30163+16acd35 (homebrew)

**Operating System:**
macOS

---

## Current behavior:
Running `circleci policy test ./policies --verbose --format junit` outputs junit xml but with timestamp missing a value, which errors when read by further tooling. 

```
<testsuite tests="13" failures="0" time="0.007" name="policies" timestamp="">
```

## Expected behavior:
This field should either be omitted or populated with a proper value.

**Comment by JulesFaucherre** [comment]
The pull request fixing this has been merged so closing the issue, don't hesitate if there is any other issue.
