### ISSUE TITLE
Error: Could not find picard image: failed to pull latest docker image: exit status 1

### ISSUE THREAD

**Issue by rcd27** [CircleCI-Public/circleci-cli#108]
I've tried to pull the required docker image with `$ docker pull {image}` and that was fine. However, trying to `$ circleci local execute` leads to such error. There is no more info about it, even in verbose mode.

What I also tried to do: `$ sudo circleci local execute` because `docker` itself runs only under `sudo`. However I got this very strange error: `Error: Unable to read config file: open .circleci/config.yml: permission denied`, but that folder and file have all permissions for all users. I think I missed something because of weak Linux skill maybe. But it can be also a problem on CircleCI CLI side. Would appreciate any help, thank you.

**Comment by rcd27** [comment]
The problem was solved by enabling `docker` to run under simple user, not `sudo`.
https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by scott-wyatt** [comment]
I know this is a closed issue, but I ran into the same issue on a Mac running Mojave 10.14.1. 
The issue was caused by already having docker installed when I did the CLI update, reinstalling circleci cli resolved this issue for me.

**Comment by antoinerousseau** [comment]
You can also try [this](https://github.com/docker/hub-feedback/issues/1098#issuecomment-316309768) or [this](https://github.com/docker/hub-feedback/issues/1098#issuecomment-335000876).
