### ISSUE TITLE
Install instructions are failing

### ISSUE THREAD

**Issue by tommaitland** [CircleCI-Public/circleci-cli#113]
I'm on MacOS 10.13 and the quick install instructions seem to be failing for me. I've run:

`bash -c "$(curl -fSl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh)"`
and
`sudo bash -c "$(curl -fSl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh)"`

Both result in this output:

```
Finding latest release.
An error occured installing the tool.
The contents of the directory /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.OEVuIyT7 have been left in place to help to debug the issue.
```

The folder it's saying has been left behind doesn't exist when trying to inspect it afterwards. Is this an issue with my system, or reproducible?

**Comment by zzak** [comment]
Hello @tommaitland!

Do you happen to have homebrew installed?

That should be a much simpler install path on a Mac. :pray:

**Comment by tommaitland** [comment]
Worked like a dream 👍
