### ISSUE TITLE
Confusing error message when docker is not running

### ISSUE THREAD

**Issue by klaaspieter** [CircleCI-Public/circleci-cli#130]
Without Docker running the `local execute` command fails with a rather unhelpful error.

```sh
$ circleci local execute
Downloading latest CircleCI build agent...
Error: Could not find picard image: failed to pull latest docker image: exit status 1
```

Starting Docker fixes it, but I had to read the source before I figured that out 😅

**Comment by marcomorain** [comment]
Hi @klaaspieter 

I get a different error on my machine (macOS):

```
$ circleci local execute -c build.yml
Docker image digest: sha256:3d88cfffd448da07ff8ced22ccdca5adc09ff18e87dc7db9b8af5b8a47647c08
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

What is the output of running `docker ps` on your machine when docker is not running?

**Comment by marcomorain** [comment]
(and thanks for the bug report 🎉 )

**Comment by klaaspieter** [comment]
That is also the error I get now after I quit the Docker.app in my menu bar (macOS).

I updated to macOS Mohave this morning so perhaps the error message I saw happens on systems that have not installed or never run Docker?

**Comment by klaaspieter** [comment]
Wow! Great turn around 💯.
