### ISSUE TITLE
Users should be able to specify target install directory

### ISSUE THREAD

**Issue by marcomorain** [CircleCI-Public/circleci-cli#153]
When installing `install.sh`, the install location [is hard coded](https://github.com/CircleCI-Public/circleci-cli/blob/2743216fe2fb5cfedc28373aa8df8851c715d1eb/install.sh#L7) to `/usr/local/bin`. Users should be able to override this location.

Perhaps specifying an argument to the script, or by setting an env var before executing it.

**Comment by bananaumai** [comment]
May i take this issue?

Do you think is it ok to use environment variable?

It will look like below.

```
$ DEST=/opt/bin && bash -c "$(curl -fSl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh)"
```

**Comment by marcomorain** [comment]
That sounds great @bananaumai - yes please. And using `DEST` is perfect 👌

**Comment by bananaumai** [comment]
@marcomorain Thanx! I made PR.
