### ISSUE TITLE
Dashes in orb names produce strange error messages

### ISSUE THREAD

**Issue by dnephin** [CircleCI-Public/circleci-cli#163]
CLI Version `0.1.3277+950a73e`

Error:
```
Error: orbs: deploy: -schedulerer0 subschemas matched instead of one
  orbs: deploy: -schedulererexpected type: String, found: Mapping
  orbs: deploy: -schedulerercommands: deploy: parameters: name: 2 schema violations found
    orbs: deploy: -schedulerercommands: deploy: parameters: name: required key [type] not found
    orbs: deploy: -schedulerercommands: deploy: parameters: name: extraneous key [cluster] is not permitted
```

Config sample:
```
orbs:                                                                                                                                                          
  deploy-schedulerer:
    ...
```

It seems that somehow the word  `deploy-schedulerer` is being split.

Changing the config to `deploy_scheduler` made the errors more readable. I'm still the other errors.

**Comment by eric-hu** [comment]
Thanks for reporting this @dnephin , this error is happening server-side. You'll see the same behavior committing this into your config and triggering a build.

We have a [ticket for this in JIRA](https://circleci.atlassian.net/browse/CIRCLE-11229), so I'll mark this as closed.
