### ISSUE TITLE
Get artifacts from the local build

### ISSUE THREAD

**Issue by rgov** [CircleCI-Public/circleci-cli#172]
My configuration has a `store_artifacts` step. I'm wondering how to get the artifacts out when I do a local build. Is it possible?

```
Uploading /root/deb to root/deb
Uploading /root/deb/blahblah.deb (54 MB): Error: FAILED with error not supported
```

**Comment by dnephin** [comment]
Currently that is not possible, so I think this is a feature request. There is a host path (the current working directory) bind mounted into the container, so we could put those files into the working directory, but I'm not sure where they would go. Maybe `.circle/local/<job name-timestamp>/artifacts/` ?

**Comment by rgov** [comment]
That would be fine for a first pass. Or, it could default to not uploading any artifacts, and require the user provide the output directory via an option.

Is there a tool in the image that gets executed to upload the artifact? Where does its source live? It would need to be able to detect whether this is a local build or not, is there a way to do that?

**Comment by dnephin** [comment]
`circleci-agent` handles running the job and steps, including the artifact upload. It is not open source at this time.

**Comment by axelssonHakan** [comment]
I'm running into a similar situation. We are running test with screen capture for chrome headless. Running i circleCI (linux) produces somewhat different screenshots than OsX or Windows. We want to be able to run it locally (which works) and be able to get the baseline images out of the container.

Maybe an option to keep the containers alive after build to be able to scp from it. Also tried the `-v` to mount into the artifacts folder but got an error during checkout that the folder wasn't empty.

**Comment by zzak** [comment]
Thanks for your post @rgov!

I agree, that this would be a great feature. However, that's entirely up to our product team to prioritize, but there's good news! If you [share your idea here](https://ideas.circleci.com/) it may convince them to let us build it sooner :)

Going to close this ticket as it's better served through our Aha app.
