### ISSUE TITLE
local execute --volumes argument is not implemented

### ISSUE THREAD

**Issue by rgov** [CircleCI-Public/circleci-cli#174]
From `build.go`:

```
flags.StringSliceVarP(&args.taskInfo.Volumes, "volume", "v", nil, "Volume bind-mounting")
```

This setting doesn't seem to be read anywhere.

**Comment by rgov** [comment]
I don't think `envVarArgs` is either.

**Comment by bradylill** [comment]
Actually this relates to why #173 is broken. We don't parse those flags with cobra and append them to the docker run command.

You can use them like you'd expect:
`circleci local execute -v "/some/local/path:/tmp/test" -e SOME_ENV_VAR=42`

**Comment by rgov** [comment]
Does it work, though? It looks like args are appended to the end of the command line, so I would assume they would go to the program in the container, and not to the docker command line tool.
