### ISSUE TITLE
Errors during config validate and update check

### ISSUE THREAD

**Issue by dotCipher** [CircleCI-Public/circleci-cli#183]
I recently installed the CLI it seems like my machine doesn't natively trust github (might be due to certificate validation that my organization does), so when I run `circleci update check` the following error occurs:
`Error: error finding latest release: Get https://api.github.com/repos/CircleCI-Public/circleci-cli/releases: x509: certificate signed by unknown authority`

On a semi-related note, when I run `circleci config validate <my_config.yml>` it fails with:
`Error: Unable to validate config: Something unexpected happened.`

Would anyone have any insight for solving this?

**Comment by rafinkarki** [comment]
I have some similar kind of issue. 
`circleci version` -> **0.1.3863+f146a5d**
And `circleci config validate` results `Error: Could not load config file at .circleci/config.yml: open .circleci/config.yml: no such file or directory` . Event though i have that file within `.circleci`. I am getting error. Is there anything that is required and i'm missing?

**Comment by eric-hu** [comment]
@dotCipher Please forgive my late response. Is this still an issue for you?

**Comment by dotCipher** [comment]
Nope, after reinstalling the newest version via the fix I mentioned in https://github.com/CircleCI-Public/circleci-cli/issues/255, this isn't a problem anymore.

**Comment by eric-hu** [comment]
Thank you for checking again! I'll mark this issue as closed since it sounds like it's resolved.
