### ISSUE TITLE
Output information on snap/brew install

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-cli#192]
It would be very helpful when troubleshooting with CLI users to know when it was installed via `snap` or `brew`. In fact, the OS as well.

I figure this information could be:

1. added to the output of the version command `circleci version`
1. added as a flag to the version command `circleci version --debug`
1. added to the diagnostic command `circleci diagnostic`
1. added to its own command `circleci about`

I'd like to see a line that shows something like `OS: <OS> <OS version>` where <OS> would be macOS, Ubuntu, Fedora, etc and then OS version number. If we really needed to keep the logic to a minimum, the OS distinguishing between `darwin` and `linux` would be enough.

Then a line such as `Installation method: <method>` where <method> could be binary, snap, or brew.

When troubleshooting, this allows us to tell users to copy & paste the output of whichever command we use and have the relevant information easily, such as with `circleci version --debug | xsel -b`.

**Comment by eric-hu** [comment]
@felicianotech This info is available in the Homebrew version if the user runs `circleci update`:

```
$ circleci update
`update` is not available because this tool was installed using `homebrew`.
Please consult the package manager's documentation on how to update the CLI.
```

I'm not sure about snap, as I don't have access to a Linux machine, but it _looks_ like this code is abstracted over the package manager:

https://github.com/CircleCI-Public/circleci-cli/blob/14aad5cadff3b514dea940e3144897cf90fadf0a/cmd/disabled.go#L41

The Homebrew version also has different help text for `update`. When running `circleci` with no arguments, it prints:

```
Available Commands:
  config      Operate on build config files
  diagnostic  Check the status of your CircleCI CLI.
  help        Help about any command
  local       Debug jobs on the local machine
  namespace   Operate on namespaces
  orb         Operate on orbs
  query       Query the CircleCI GraphQL API.
  setup       Setup the CLI with your credentials
  update      This command is unavailable on your platform
  version     Display version information
```

It seems pretty simple to tweak the output here if that's insufficient. What do you think about the current state?

**Comment by felicianotech** [comment]
Looks like Homebrew is suppose to be detected with PackageManager is set to `homebrew` during build time. Problem is, I can't find where that is done. GoReleaser sets it to `release`.

**Comment by rykimcircle** [comment]
This is currently already a feature when you run `circleci version` in the latest version of the cli!
