### ISSUE TITLE
`circleci tests split` requires circleci-agent

### ISSUE THREAD

**Issue by juanca** [CircleCI-Public/circleci-cli#196]
Hello! 

As a means of exploring with optimizations for our workflow pipeline, I've recently started using the `circleci` CLI locally. I ran into a problem when testing the `circleci tests split` command. 

```
~/workspace/project (branch-name *) $ circleci tests glob "{spec,engines}/**/*_spec.rb" | circleci tests split --split-by=timings
Error: Please ensure that circleci-agent is installed, expected this to be called inside a job: exec: "circleci-agent": executable file not found in $PATH
```

Where can I download the `circleci-agent`? And is there really a strict necessity for the additional binary?

**Comment by juanca** [comment]
Okay. I'll close this issue.

**Comment by nathanielford** [comment]
A friendly note: you explicitly call out using the `circleci-cli` when determining the configuration of unit test splitting: https://circleci.com/docs/2.0/parallelism-faster-jobs/#using-the-circleci-cli-to-split-tests

`circleci tests glob` will indicate *what* tests will get split out, but shows no indication of *how* they'll be split. It would be awesome if we could test each element of our build process locally so that we can be sure of correctness, but this is definitely friction in that direction.

**Comment by alxtz** [comment]
In the newest version, `circleci tests glob` somehow also requires circleci-agent to be present, is this a know issue?
![image](https://user-images.githubusercontent.com/16031425/76390566-9a251b00-63a8-11ea-9038-5c15a520f891.png)

**Comment by Vanals** [comment]
> circleci-agent

Having the same issue! Did you find any solution?

**Comment by exarkun** [comment]
> The `circleci-agent` is automatically inside a build running in our system. In general, `circleci tests split` is meant to be used inside your jobs. In general you use `circleci tests glob` to see how tests would get split out locally.

It's not clear this is necessarily the case.  [Here is a CircleCI configuration](https://github.com/exarkun/tahoe-lafs/blob/18057233fd170279d768ca5347cba91638ff8dbe/.circleci/config.yml) with [a job named "integrationtest"](https://github.com/exarkun/tahoe-lafs/blob/18057233fd170279d768ca5347cba91638ff8dbe/.circleci/config.yml#L377) which attempts to use [`circleci tests glob` and `circleci tests split`](https://github.com/exarkun/tahoe-lafs/blob/18057233fd170279d768ca5347cba91638ff8dbe/.circleci/config.yml#L407) but which fails with an error suggesting the agent is not installed:

> Error: Please ensure that circleci-agent is installed, expected this to be called inside a job: exec: "circleci-agent": executable file not found in $PATH
> Error: Please ensure that circleci-agent is installed, expected this to be called inside a job: exec: "circleci-agent": executable file not found in $PATH

No doubt this is a result of something declared in the config file - but it's not clear what, and it seems to demonstrate that not _all_ jobs get `circleci-agent` installed automatically.

**Comment by yamenarahman** [comment]
`circleci local execute <job_name>` ie `circleci local execute build`
