### ISSUE TITLE
Linux amd64 asset missing in v0.1.4029 release

### ISSUE THREAD

**Issue by MarcelMue** [CircleCI-Public/circleci-cli#200]
Previous releses such as v0.1.4005 always included a linux asset eg:
`circleci-cli_0.1.4005_linux_amd64.tar.gz`

The latest release is missing the linux asset, the `install.sh` also fails because of this on linux:
```
curl -fLSs https://circle.ci/cli | bash
Installing CircleCI CLI
Finding latest release.
Downloading CircleCI v0.1.4029
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
An error occured installing the tool.
The contents of the directory /tmp/tmp.Hx8hnDm6Xc have been left in place to help to debug the issue.
```

The asset should be added to that release if this was not intended. Otherwise the installation process should be adapted to support the situation properly.

**Comment by MarcelMue** [comment]
Link to the release on github:

**Comment by marcomorain** [comment]
That was weird - looks like a transient network error uploading the binaries to the release.

I've just re-build the job, and it has published binaries now.

Can you give it another try please @MarcelMue ?

**Comment by MarcelMue** [comment]
Thanks, works now :+1:

**Comment by marcomorain** [comment]
Sorry for this Marcel, thanks for reaching out and taking the time to log the issue.
