### ISSUE TITLE
Command to trigger a new build

### ISSUE THREAD

**Issue by gionn** [CircleCI-Public/circleci-cli#202]
Hi,

sometimes I need to trigger a new build for the last commit on a particular project, it would be great to do this with the CLI instead to use the GUI or to maintain an ugly curl script.

Thanks.

**Comment by zzak** [comment]
Thanks for your post @gionn!

I agree, that this would be a great feature. However, that's entirely up to our product team to prioritize, but there's good news! If you [share your idea here](https://ideas.circleci.com/) it may convince them to let us build it sooner :)

Going to close this ticket as it's better served through our Aha app.
