### ISSUE TITLE
Cannot use character `/` in development orb's tags/versions

### ISSUE THREAD

**Issue by h-matsuo** [CircleCI-Public/circleci-cli#213]
### Problem:

According to the [CircleCI's document](https://circleci.com/docs/2.0/creating-orbs/#development-and-production-orbs-versioning-semantics), development orbs can be tagged with the format like `dev:<string>`, and the following tag is a valid:

```
"dev:myinitials/mybranch"
```

However, if you try to publish an orb using the above tag, following error message will be shown:

```
$ circleci orb publish src/orb.yml hoge/fuga@dev:myinitials/mybranch
Error: Invalid orb reference 'hoge/fuga@dev:myinitials/mybranch': Expected a namespace, orb and version in the format 'namespace/orb@version'
```

### Will be in trouble when:

Consider you make CircleCI to automatically publish the development orb tagged with a git branch name. If you create a branch named `feature/prepare-v1.0.0`, publishing will be failed because the branch name contains the character `/`.

### Environment:

macOS 10.14.1

```
$ circleci version
0.1.4211+14dfd68
```

**Comment by h-matsuo** [comment]
I opened a pull request related to this issue: #214

**Comment by zzak** [comment]
This should be fixed now, thanks for your report @h-matsuo!

Please send us a pull request to add your name to [CONTRIBUTORS.md](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTORS.md)! :bow:

**Comment by h-matsuo** [comment]
@zzak I've sent a PR: #218
I'm very glad to be listed as one of contributors. Thanks!
