### ISSUE TITLE
Can I skip the update check?

### ISSUE THREAD

**Issue by rgov** [CircleCI-Public/circleci-cli#228]
I have a small script that drops me into a bash session inside a container using the same image I use for builds on CircleCI. I use the `circleci` CLI to canonicalize the YAML configuration so I can slice up the output and figure out the name of the image. But it's slow because the CLI will do an update check each time before it processes the YAML.

Is there a way to disable the update check?

**Comment by dnephin** [comment]
There is a hidden flag: https://github.com/CircleCI-Public/circleci-cli/issues/226#issuecomment-446263215

`--skip-update-check`

**Comment by rgov** [comment]
Confirmed that it works. Thank you!

**Comment by marcomorain** [comment]
`CIRCLECI_CLI_SKIP_UPDATE_CHECK=1` should work too, but I’ve not tested it.
