### ISSUE TITLE
Install fails on WSL

### ISSUE THREAD

**Issue by dotCipher** [CircleCI-Public/circleci-cli#255]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Running the default install instructions fails using Ubuntu on WSL (Windows 10).  The exact command and output are:
```
curl -fLSs https://circle.ci/cli | bash
Installing CircleCI CLI
Finding latest release.
An error occured installing the tool.
The contents of the directory /tmp/tmp.mbdGoUMhPY have been left in place to help to debug the issue.
```

And the temp directory of `/tmp/tmp.mbdGoUMhPY` is empty with no contents.  The same behavior happens when running with `sudo`.

**What is the expected behavior?**

Expected behavior would be that the circleci cli gets successfully installed.

**Which version of the CLI and OS are you using? Did this work in previous versions?**

N/A on CLI version.
`Linux 4.4.0-17134-Microsoft #471-Microsoft Fri Dec 07 20:04:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux` running on `Windows 10 Pro`

I noticed that a similar problem occurred in #113, but since I am not running a Mac, I am unable to use homebrew.

**Comment by john-mcgowan-wowza** [comment]
the issues is that since all the repos were at github, both of the keys authenticated properly at github, and since the more restrictive key is authenticated first, I couldn't pull the repo.


/John

________________________________

**Comment by rjlopezdev** [comment]
@dotCipher same issue.

This worksfork me in __OpenSuse WSL__:

```bash
curl -fLSs https://circle.ci/cli | DESTDIR=/home/your_user_name bash
```

**Comment by eric-hu** [comment]
@dotCipher is this still an issue for you? It sounds like there were a couple of fixes in this thread. Please let us know if they worked when you get a chance.

**Comment by dotCipher** [comment]
Apologies on the delayed response, I ran the fix:
```
curl -fLSs https://circle.ci/cli | sudo bash
```
and that worked like a charm, thanks!

**Comment by eric-hu** [comment]
Thanks for checking that again! It sounds like this is now resolved, so I'll mark this issue as closed.

**Comment by kwuite** [comment]
@john-mcgowan-wowza ,

You mentioned to report back in case "dotcipher" came across this issue: `Error: failed to start event processor: failed to compute task config: failed to read config file: open circle.yml: no such file or director`.

I am experiencing this error on WSL ubuntu 18. It seems as if you know how to resolve this error. Would you mind sharing your insights in this issue: #316 .

Thanks in advance.

**Comment by IgorKurkov** [comment]
same issue

**Comment by limfjm** [comment]
I encountered the same issue and was able to run it using the following steps.

Error: failed to load yaml config from config path provider: Could not load config file at .circleci/config.yml: open .circleci/config.yml: no such file or directory

Ubuntu-22.04
WSL v2
0.1.29314+148495a (release)

1.  sudo chmod 777 /usr/local/bin/    -   (feel free to update the permission level you want)
2. curl -fLSs https://circle.ci/cli | sudo bash
3. cd PATH_DIRECTORY   -    (e.g. cd /mnt/d/development-project/github/infrastructure-as-code)
4. Make sure to enable the Docker Desktop - Resources WSL integration
5. sudo circleci local execute deploy
