### ISSUE TITLE
local execute - filenames with spaces cause code checkout to fail

### ISSUE THREAD

**Issue by LachlanStuart** [CircleCI-Public/circleci-cli#271]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Running CircleCI jobs locally via CLI fails on the "Checkout code" step if any directory names or filenames in the git repository contain spaces.

Can you provide an example?

```bash
git clone https://github.com/CircleCI-Public/circleci-demo-go.git
cd circleci-demo-go
touch "filename with spaces.txt"
git add "filename with spaces.txt"
git commit -m "add filename with spaces.txt"
circleci local execute --job build
```

Output:

```
Docker image digest: sha256:2467cdef08aa5988c09618d33c0182cc31cf46b5e3be92e65f08447b01c96929
====>> Spin up Environment
Build-agent version 0.1.1578-6ce10866 (2019-02-02T19:43:16+0000)
Starting container circleci/golang:1.8
  using image circleci/golang@sha256:19be339aac6a708434981f4e3a2ee79c45eca9af313c49b156fe021c1b0a0b74
Starting container circleci/postgres:9.6-alpine
  using image circleci/postgres@sha256:a4b18d3e451ac84955cb33c372389a46ce06e46439ec391e168eec9b607114ff
====>> Container circleci/postgres:9.6-alpine
Service containers logs streaming is disabled for local builds
You can manually monitor container 40f0cf214d9c4b674d2c1e5adf0bcabded0a09a19c71d8ce27f5cc6ba2f03548
====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /go/src/github.com/CircleCI-Public/circleci-demo-go && cd /tmp/_circleci_local_build_repo && git ls-files | xargs tar -c | tar -x -C /go/src/github.com/CircleCI-Public/circleci-demo-go
tar: filename: Cannot stat: No such file or directory
tar: with: Cannot stat: No such file or directory
tar: spaces.txt: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Error: Exited with code 123
Step failed
```

**What is the expected behavior?**

"Checkout code" step succeeds

**Which version of the CLI and OS are you using? Did this work in previous versions?**

CircleCI: 0.1.5314+26252a9 (installed via `curl -fLSs https://circle.ci/cli | sudo bash`)
OS: Ubuntu 18.04.1 LTS

Have not tried previous versions

Please provide the output of `circleci version` and `circleci diagnostic`.

```
> circleci version
0.1.5314+26252a9
> circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /home/lachlan/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.

> docker version
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.10.1
 Git commit:	7390fc6
 Built:	Wed Apr 18 01:23:11 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	18.06.1-ce
  API version:	1.38 (minimum version 1.12)
  Go version:	go1.10.4
  Git commit:	e68fc7a
  Built:	Mon Oct  1 14:25:33 2018
  OS/Arch:	linux/amd64
  Experimental:	false

```

**If you have any questions, feel free to ping us at @CircleCI-Public/dx-clients.**

**Comment by eddiewebb** [comment]
Thanks for the report @LachlanStuart !

This was introduced in #151 , and I have just tested a change in the `build-agent` to address this.  Unfortunately it will take a few days for that to get published.

In the interim you can force circleCI to use a previous version without that change by editing `~/.circleci/build_agent_settings.json `

The latest previous version before the bug looks to be `sha256:f340abec0d267609a4558a0ff74538227745ef350ffb664e9dbb39b1dfc20100` and is respecting files names with spaces locally (but will not respect .gitignore as described in #151)

i.e.


#### ~/.circleci/build_agent_settings.json 
```
{"LatestSha256":"sha256:f340abec0d267609a4558a0ff74538227745ef350ffb664e9dbb39b1dfc20100"}
```

**Comment by eddiewebb** [comment]
Adding [link to internal PR](https://github.com/circleci/build-agent/pull/852) that is blocking this, and I will continue to push that on our side.

**Comment by eddiewebb** [comment]
@LachlanStuart, thanks for your patience. This is now resolved.  Please confirm by running `circleci update build-agent` and running your project again.

**Comment by LachlanStuart** [comment]
@eddiewebb The fix worked. Thanks for your help.

**Comment by gms8994** [comment]
@eddiewebb It looks like this hasn't been fixed in the latest version that is `brew` installable, but the fix described for updating the sha256 value does work; thought I'd drop a note.

**Comment by eddiewebb** [comment]
@gms8994 - thank you.

Can you confirm you also ran `circleci update build-agent`  after brew install?  Want to be sure you actually got the latest agent used by the CLI.

**Comment by gms8994** [comment]
```
circleci update build-agent
`update` is not available because this tool was installed using `homebrew`.
Please consult the package manager's documentation on how to update the CLI.
```

I installed the CLI fresh this morning, so I should have the latest available.

**Comment by gms8994** [comment]
```
circleci version
0.1.5607+f705856
```

in case it's needed

**Comment by eddiewebb** [comment]
Thanks @gms8994 - can you also provide OS & Version?

**Comment by gms8994** [comment]
Apologies, I should have included those! MacOS Mojave 10.14.4.

**Comment by eddiewebb** [comment]
I just merged some pending changes, new agent sha should be `51ece12fd08090ea5ef2bc03374211fe82c86dc185da43bf4ee351a45398b77a`

Can you run `circleci build` and share the first ~5 lines to confirm version

```
$ circleci build -c foo.yml 
Downloading latest CircleCI build agent...
Docker image digest: sha256:51ece12fd08090ea5ef2bc03374211fe82c86dc185da43bf4ee351a45398b77a
====>> Spin up Environment
Build-agent version 1.0.11707-7454d6d0 (2019-05-22T13:36:03+0000)
```

**Comment by gms8994** [comment]
Maybe there's something else I need to do first?

```
circleci build -c .circleci/config.yml 
Docker image digest: sha256:f340abec0d267609a4558a0ff74538227745ef350ffb664e9dbb39b1dfc20100
====>> Spin up Environment
Build-agent version 0.1.1562-54910180 (2019-01-31T15:18:35+0000)
Starting container circleci/php:7.1-node-browsers
  using image circleci/php@sha256:12ebf5607ce13e26bed447c445bff8de17200b1c5c59ef825040d5176f8d7c85
Starting container circleci/mysql:5.7
  using image circleci/mysql@sha256:e4f47d79c30fa2b79d160d70b36973e3daeeb8ecdf3b85edd5607a35f65e5d4e
```

**Comment by eddiewebb** [comment]
Thanks @gms8994 - sad news.  Apparently something changed in the way we package for homebrew and it is out of date, and does not have a upgrade path.

To use the latest build-agent (a dependency of CLI) you will need to 

```
brew uninstall circleci
curl -fLSs https://circle.ci/cli | bash
```

And then you should be able to `circleci update agent` and run a local build.
