### ISSUE TITLE
circleci setup --token doesn't work

### ISSUE THREAD

**Issue by oprogramador** [CircleCI-Public/circleci-cli#273]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
I type `circleci setup --token <my-token>` but it still asks me for the token.

On the other hand `echo -e "y\n<my-token>" | circleci setup` outputs:
```
✔ A CircleCI token is already set. Do you want to change it: y

Error: Error reading token: EOF
```
I need an automatic way to authenticate in order to use it in CI to publish automatically CircleCI orbs.

**What is the expected behavior?**
It should successfully authenticate me.

**Which version of the CLI and OS are you using? Did this work in previous versions?**
circleci-cli: 0.1.3723+1dca9bc
OS: Mac OS X 10.12.6

I haven't tried it in any previous version.

**Comment by oprogramador** [comment]
a workaround:
```
(echo y && sleep 1 && echo -e "<my-token>" && sleep 1 && echo https://circleci.com) | circleci setup
```

**Comment by zzak** [comment]
Hello @oprogramador!

Thank you for writing in.

Could you try using `--no-prompt` in combination with the command you mentioned above?

So like,

```
$ circleci setup --no-prompt --token <your-token>
```

Let me know if that helps! Thanks!

**Comment by oprogramador** [comment]
@zzak 

`--no-prompt` works, thanks
