### ISSUE TITLE
Fix install.sh on OSX <10.11

### ISSUE THREAD

**Issue by patcon** [CircleCI-Public/circleci-cli#274]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

First off, thanks for maintaining this tool! :)

**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
`curl -fLSs https://circle.ci/cli | bash` fails on osx

Can you provide an example?
```
$ curl -fLSs https://circle.ci/cli | bash
Installing CircleCI CLI
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
```

**What is the expected behavior?**
Install should work.

This should fix it:
https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x

**Which version of the CLI and OS are you using? Did this work in previous versions?**
osx 10.10 (newest cli)

Please provide the output of `circleci version` and `circleci diagnostic`.
```
# after install
$ circleci version
0.1.5389+4379bab
```

**If you have any questions, feel free to ping us at @CircleCI-Public/dx-clients.**

**Comment by zzak** [comment]
Hello @patcon,

Thank you for your report.

While I don't have a mac to test this on, some other people here should.

In the mean time, you might want to try `brew install circleci` as an alternative.

Sorry for the trouble!

**Comment by subuta** [comment]
In my case, `curl` command for getting latest release of Github failed with `API rate limit exceeded` error. but not shown at install command (`curl -fLSs https://circle.ci/cli | bash`) execution because of `--silent` option.

Fixed by adding `-H "Authorization: token ${your_gh_personal_access_token_goes_here}"` to curl command(at 25 of `install.sh`).

https://github.com/CircleCI-Public/circleci-cli/blob/master/install.sh#L25

**Comment by eric-hu** [comment]
@patcon I was unable to reproduce this with macOS 10.12.6 (Sierra):

```
$ curl -fLSs https://circle.ci/cli | bash
Installing CircleCI CLI
Finding latest release.
Downloading CircleCI v0.1.5389
Installing to /usr/local/bin
/usr/local/bin/circleci
```

The StackOverflow link you pasted does note that this applies only to OS X prior to 10.11. Can you confirm that you're on a version earlier than 10.11?

**Comment by patcon** [comment]
@subuta this seems like an unrelated issue. (It's best to keep issues specific, for the sanity of the maintainers <3) It def sounds like it could be important though, so pls do open another ticket :)

@eric-hu Ah yep, I'm on 10.10.5 :)

>  If no arguments are passed or if only the -d flag is passed mktemp behaves as if -t tmp was supplied.

https://ss64.com/osx/mktemp.html

So if you found it acceptable, you could change `mktemp -d` to `mktemp -d -t tmp`, and it would be the same :) (It should be redundant for more current `mktemp` versions, but will helpfully fix for old versions.)

**Comment by subuta** [comment]
@patcon Thanks for reply, deleted unrelated comments, sorry :)

**Comment by eric-hu** [comment]
Thank you for confirming @patcon ! I opened a PR and hope to get a review soon.

**Comment by eric-hu** [comment]
@patcon the change is merged. Could you try the `curl -fLSs https://circle.ci/cli | bash` installation command again and let us know if it works for you?

**Comment by patcon** [comment]
Yep! It completes install now!

```
$ curl -fLSs https://circle.ci/cli | bash
Starting installation.
Installing CircleCI CLI v0.1.5607
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
Installing to /usr/local/bin
/usr/local/bin/circleci
```

Though for totaly clarity, it outputs the help text from the first incantation of the command that fails on my end. But that's just a cosmetic thing :)
