### ISSUE TITLE
`circleci local execute` yields `error authentication with ECR: AWS credentials not found`

### ISSUE THREAD

**Issue by timvisher** [CircleCI-Public/circleci-cli#280]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Can't run a circleci config locally with a private ECR repo.

`circleci local execute`

Yields:

```
Docker image digest: sha256:627a3ccc6a69281fc4c8a69b39f156d45c3e2ccafbb6323414688ba02424c5c4
====>> Spin up Environment
Build-agent version 1.0.8534-fa52d0c9 (2019-03-04T10:32:10+0000)
Error: 
error authentication with ECR: AWS credentials not found

Step failed
Task failed
```

**What is the expected behavior?**

Should run.

**Which version of the CLI and OS are you using? Did this work in previous versions?**

Yes.

```
$ circleci version
0.1.5432+9ea4b64
$ lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
$ circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /home/vagrant/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Tim Visher.
```

**If you have any questions, feel free to ping us at @CircleCI-Public/dx-clients.**

**Comment by dmosorast** [comment]
Also seeing this with version `0.1.5490+82d3083`, the OS information is identical and diagnostic is comparable.

**Comment by hasanmasood** [comment]
I’m also seeing this issue

**Comment by royvandewater** [comment]
Just to confirm, are you passing the AWS authentication information in to the `docker` stanza as described here? https://circleci.com/blog/aws-ecr-auth-support/

```yaml
    docker:
      - image: account-id.dkr.ecr.us-east-1.amazonaws.com/org/repo:0.1
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID_STAGING
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY_STAGING
```

If so, then the AWS credentials will need to be passed in to the environment using:

```shell
circleci local execute \
  --env AWS_ACCESS_KEY_ID_STAGING=<key> \
  --env AWS_SECRET_ACCESS_KEY_STAGING=<secret>
```

**Comment by gitizenme** [comment]
Yes, using the `docker` stanza and experiencing the same error with this version:

```
$ circleci version 
0.1.5879+416032d

$ circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/joe/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
Hello, Joe Chavez.
```

**Comment by pbaettig** [comment]
@gitizenme Did you get this to work? I'm facing the exact same issue... not sure if it's a bug or PEBKAC 😅

**Comment by nsctrl** [comment]
@pbaettig @gitizenme Made it working by defining missing environmental variables that were called in config.yml.

```
circleci local execute \
--job <job_name> \
--env AWS_ACCESS_KEY_ID=<id> \ 
--env AWS_SECRET_ACCESS_KEY=<key> \
--env AWS_DEFAULT_REGION=<region> \
--env AWS_ECR_ACCOUNT_URL=<account_url>
```
It happened because I used `circleci config process` to generate `version: 2` from `version: 2.1 ` config.yml.

**Comment by marcomorain** [comment]
I believe that this a documentation issue – when supplying all of the requried environment variables it works as intended.

**Comment by rykimcircle** [comment]
This issue has been resolved the documentation describes how to pass environment variables [here](https://circleci.com/docs/how-to-use-the-circleci-local-cli) please let us know if this is still causing issues or need any clarifications. Thanks!
