### ISSUE TITLE
Snap Under Manual Review

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-cli#287]
The snap deploys are currently paused as the CLI snap is under a manual review (revision # 136). Once the review is over, deploys should resume.

I've reached out on their forum: https://forum.snapcraft.io/t/circleci-snap-flagged-for-manual-review/10387

**Comment by felicianotech** [comment]
The latest snap has been released. The next build on `master` should publish the snap without issue.

**Comment by eric-hu** [comment]
Thanks for the update! After a "re-run from failed" on the last master workflow, snap indeed published successfully:

https://circleci.com/gh/CircleCI-Public/circleci-cli/5495
