### ISSUE TITLE
"Something unexpected happened" running `circleci config check` with CircleCI Enterprise

### ISSUE THREAD

**Issue by codelemur** [CircleCI-Public/circleci-cli#288]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Following the setup instructions I've run the following:

* `brew install circleci`
* `circleci setup`
* I entered my enterprise user api token (not project)
* Entered directory with `.circleci/config.yaml`
* run `circleci config check`

I receive the output: `Error: Unable to validate config: Something unexpected happened.`

I then did the following:

* `circleci config check --debug`
yielding 
```
>> variables: map[config:version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-browsers
    environment:
      NODE_ENV: test
    steps:
      - run: node --version; npm --version
      - checkout
      - run: npm install; npm install --no-save typescript
      - run: npm run test:ci
]
>> query: 
                query ValidateConfig ($config: String!) {
                        buildConfig(configYaml: $config) {
                                valid,
                                errors { message },
                                sourceYaml,
                                outputYaml
                        }
                }
<< request id: 0dc3442c-b389-44dc-b70d-3059d3da939c
<< result status: 200 OK
<< {"data":{"buildConfig":null},"errors":[{"message":"Something unexpected happened.","type":"INTERNAL","locations":[{"line":2,"column":42}],"query-path":["buildConfig"],"arguments":{"configYaml":"$config"}}]}
Error: Unable to validate config: Something unexpected happened.
```
Can you provide an example?

**What is the expected behavior?**
I expect this to validate the configuration provided without errors, or at least provide information as to the internal error that requires fixing.

**Which version of the CLI and OS are you using? Did this work in previous versions?**
Please provide the output of `circleci version` and `circleci diagnostic`.
MacOS: `10.12.6`
CLI version: `0.1.4786+bad101f`
```
$ circleci version
0.1.4786+bad101f

========================
$ circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/<me>/.circleci/cli.yml
API host: https://circleci.<enterprise-host>.com/
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
```

**Comment by marcomorain** [comment]
cc @KunalJain

**Comment by rykimcircle** [comment]
This appears to have been resolved, if this problem is still occurring please create a new issue! :D
