### ISSUE TITLE
I am not able to do local execute - well known permission denied

### ISSUE THREAD

**Issue by smiklosovic** [CircleCI-Public/circleci-cli#290]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

    [smiklosovic@E091-FED circleci]$ circleci local execute -c .circleci/config.yml  --job hello-build --skip-checkout 
    Docker image digest: 
    sha256:8f7aa2f671ed787514041bd4d57d8ec327a401f3eb62582cf5839931554d908b
    Error: failed to start event processor: failed to compute task config: failed to read config file: open .circleci/config.yml: permission denied
    [smiklosovic@E091-FED circleci]$ pwd
    /home/smiklosovic/dev/circleci
    [smiklosovic@E091-FED circleci]$ cat .circleci/config.yml 
    version: 2
    jobs:
        hello-build:
        docker:
            - image: circleci/buildpack-deps:curl-browsers
        steps:
            - run:
                command: echo "Hello ${CIRCLE_USERNAME}"
            - run:
                command: |-
                    echo "TRIGGERER: ${CIRCLE_USERNAME}"
                    echo "BUILD_NUMBER: ${CIRCLE_BUILD_NUM}"
                    echo "BUILD_URL: ${CIRCLE_BUILD_URL}"
                    echo "BRANCH: ${CIRCLE_BRANCH}"
                    echo "RUNNING JOB: ${CIRCLE_JOB}"
                    echo "JOB PARALLELISM: ${CIRCLE_NODE_TOTAL}"
                    echo "CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}"
                name: Show some of the CircleCI runtime env vars
            - run:
                command: |-
                    echo "uname:" $(uname -a)
                    echo "arch: " $(arch)
        name: Show system information

Can you provide an example?

**What is the expected behavior?**

it will run my job locally

**Which version of the CLI and OS are you using? Did this work in previous versions?**

    [smiklosovic@E091-FED circleci]$ circleci version
    0.1.5490+82d3083
    [smiklosovic@E091-FED circleci]$ uname -a
    Linux E091-FED 4.20.16-200.fc29.x86_64 #1 SMP Thu Mar 14 15:10:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
    [smiklosovic@E091-FED circleci]$ cat /etc/redhat-release 
    Fedora release 29 (Twenty Nine)

Please provide the output of `circleci version` and `circleci diagnostic`.

[smiklosovic@E091-FED circleci]$ circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /home/smiklosovic/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
Hello, Štefan Miklošovič.

[smiklosovic@E091-FED circleci]$ docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-65.git1185cfd.fc29.x86_64
 Go version:      go1.11.5
 Git commit:      1185cfd/1.13.1
 Built:           Tue Feb 12 17:46:58 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-65.git1185cfd.fc29.x86_64
 Go version:      go1.11.5
 Git commit:      1185cfd/1.13.1
 Built:           Tue Feb 12 17:46:58 2019
 OS/Arch:         linux/amd64
 Experimental:    false

**If you have any questions, feel free to ping us at @CircleCI-Public/dx-clients.**

**Comment by marcomorain** [comment]
@smiklosovic we have overhauled how this system works when we added support for config version 2.1 in local builds. Could you verify if this is still an issue, please? I believe that it should be fixed.
