### ISSUE TITLE
 circleci orb list ledger reports published orbs as "(Not published)"

### ISSUE THREAD

**Issue by lokst** [CircleCI-Public/circleci-cli#292]
- [x ] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x ] I have checked for similar issues and haven't found anything relevant.
- [x ] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**
Reporting a bug

**What is the current behavior?**
`circleci orb list ledger` shows a list of orbs, and all of them are shown as "(Not published)", but in fact 2 of them are present in the Orb registry.

Can you provide an example?
`circleci orb list ledger`

**What is the expected behavior?**
ledger/chef and ledger/docker should not be shown as "(Not published)"

**Which version of the CLI and OS are you using? Did this work in previous versions?**
0.1.5490+82d3083 on macOS
Unclear if it worked in previous versions

Please provide the output of `circleci version` and `circleci diagnostic`.

circleci version shows `0.1.5490+82d3083`

circleci diagnostic shows:

```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/stellalok/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Stella Lok.
```

**If you have any questions, feel free to ping us at @CircleCI-Public/dx-clients.**

**Comment by lokst** [comment]
Found another case of this, for a different namespace

**Comment by eric-hu** [comment]
Yep, this looks like an issue with the GQL response itself. I checked in Apollo with Zach and found the versions are missing in that response too.

**Comment by marcomorain** [comment]
@lokst has confirmed that this is still an issue as of 11 March 2020.

**Comment by aengelberg** [comment]
This has been fixed on the backend, so no CLI version update required.
