### ISSUE TITLE
Circleci CLI does not install correctly via curl Permission Denied

### ISSUE THREAD

**Issue by marcusjwhelan** [CircleCI-Public/circleci-cli#293]
- [x ] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x ] I have checked for similar issues and haven't found anything relevant.
- [x ] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Cannot install circleci on ubuntu using curl command. Prefer not to install items with snap. Everything I have installed with snap crashes my Ubuntu

Can you provide an example?
both provied curl commands fail
```
sudo curl -fLSs https://circle.ci/cli | bash
sudo curl -fLSs https://circle.ci/cli | DESTDIR=/opt/bin bash
```

**What is the expected behavior?**
install and work

**Which version of the CLI and OS are you using? Did this work in previous versions?**
Ubuntu 18.04.2 LTS x86_64
Kernel: 4.18.0-17-generic
shell: bash 4.4.19
DE: GNOME 3.28.3
WM: GNOME Shell
Terminal: gnome-terminal

Please provide the output of `circleci version` and `circleci diagnostic`.

With `sudo curl -fLSs https://circle.ci/cli | bash`
```
Starting installation.
Installing CircleCI CLI v0.1.5490
Installing to /usr/local/bin
mv: cannot move 'circleci' to '/usr/local/bin/circleci': Permission denied
An error occured installing the tool.
The contents of the directory /tmp/tmp.Hy1GTtpEgu have been left in place to help to debug the issue.
```
With `sudo curl -fLSs https://circle.ci/cli | DESTDIR=/opt/bin bash`
```
Starting installation.
Installing CircleCI CLI v0.1.5490
Installing to /opt/bin
mv: cannot move 'circleci' to '/opt/bin': Permission denied
An error occured installing the tool.
The contents of the directory /tmp/tmp.6WX9FCJY8J have been left in place to help to debug the issue
```

I am able to cd to `/tmp/tmp.6WX9FCJY8J` and execute `./circleci` and that works. But it says it fails, and is not installed to my bash profile?

**Comment by marcusjwhelan** [comment]
Was able to use circleci if I manually moved the file with `sudo mv circleci /usr/local/bin` from that tmp directory.

**Comment by MateusAndrade** [comment]
> Was able to use circleci if I manually moved the file with `sudo mv circleci /usr/local/bin` from that tmp directory.

Same here

**Comment by successanil** [comment]
> run the bash part of it with `sudo` as in `curl -fLSs https://circle.ci/cli | sudo bash` ... this solved it for me ...

Even this worked for me also. I'  m trying on ubuntu. Thanks a lot.
