### ISSUE TITLE
CircleCI process breaks folded YAML strings

### ISSUE THREAD

**Issue by jemc** [CircleCI-Public/circleci-cli#295]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**

It's a bug. This applies to both `circleci process` and also to the CircleCI service itself, which I assume is using `circleci process` under the hood.

**What is the current behavior?**

The `circleci process` command converts "folded" multiline YAML string literals into non-folded ones. See https://yaml-multiline.info/ to read about the difference between the two if you're not aware.

For example, consider the following snippet as input:
```yaml
          command: >
            docker build
              -t $AWS_ECR_ACCOUNT_URL_US_EAST_1/<< parameters.image >>
              << parameters.subdir >>
```

Running `circleci process` converts it to the following snippet, which is not semantically the same in how the line breaks are processed:
```yaml
        command: |
          docker build
            -t $AWS_ECR_ACCOUNT_URL_US_EAST_1/cp-api
            cmd/api
```

The result is that a valid YAML multi-line literal that should get folded into a single line is instead treated as multiple lines by the shell executor, seen as three (invalid) shell commands instead of one.

I can work around this by using `|` and adding a `\` on the end of each line in the literal to make the shell executor fold the lines together, but the fact remains that `circleci process` is breaking what would otherwise be a valid YAML representation of what I want to do. Also, the `\` workaround may not work for non-shell semantics.

**What is the expected behavior?**

I expect `circleci process` not to affect the YAML semantics of my string literals at all. I don't mind if it changes the formatting of the YAML markup, as long as the string literals themselves remain identical to what I gave as input.

This means that `circleci process` should either preserve the `>` vs `|` distinction, or alternatively, eagerly fold my folded string literal onto a single line.

**Which version of the CLI and OS are you using? Did this work in previous versions?**

```
$ circleci version
0.1.5546+1fae6c8

$ circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /home/jemc/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
Error: please set a token with 'circleci setup'
You can create a new personal API token here:
https://circleci.com/account/api
```

**Comment by marcomorain** [comment]
Hi @jemc - the CLI tool is behaving as expected here, it's the YAML spec that's causing the confusion :(

Here is an example of parsing the the input and output commands that you have given, using Python: (`circleci config process` is using Clojure and the `SnakeYAML` library, not Python, under the hood):

`parse.py`:

```python
#!/usr/bin/env python3
import yaml
import json

with open("example.yaml", 'r') as stream:
  print(json.dumps(yaml.safe_load(stream)))
```

`example.yml`:

```yaml
command_a: >
  docker build
    -t cp-api
    cmd/api
command_b: |
  docker build
    -t cp-api
    cmd/api
command_c: >
  docker build
  -t cp-api
  cmd/api
```

```
marc@blaster ~/dev/circleci/circle $ python3 parse.py | jq .
marc@blaster ~/dev/circleci/circle $ python3 parse.py | jq .
{
  "command_a": "docker build\n  -t cp-api\n  cmd/api\n",
  "command_b": "docker build\n  -t cp-api\n  cmd/api\n",
  "command_c": "docker build -t cp-api cmd/api\n"
}
```

Can see that `command_a` and `command_b` have the same line break after `docker build`. The indentation in `command_c` is what you need.

This has tripped many people up over the years using Yaml (including us internally at CircleCI). Yaml is an "interesting" spec to put it mildly.
