### ISSUE TITLE
Homebrew has some issue updating to the latest release version

### ISSUE THREAD

**Issue by chenrui333** [CircleCI-Public/circleci-cli#303]
relates to https://github.com/CircleCI-Public/circleci-cli/issues/256
Also relates to https://github.com/Homebrew/homebrew-core/pull/39797/

Basically, I am not quite sure how to introduce `packr` process into the formula testing.

Might need some eyes and help on this.

**Comment by zzak** [comment]
Hello @chenrui333!

Thank you for your help on this!! :bow:

I've been meaning to get around to this, sorry for the delay.

I think all we need to do is make sure `make pack` is run prior to `go build` command in the formula.

Would you mind giving that a shot and report your findings?

Thanks!

**Comment by chenrui333** [comment]
yeah, that seems what I saw in the travis build as well, but not quite sure how the install process would look like for `make pack`, I will give a try. 😄

**Comment by zzak** [comment]
Thanks @chenrui333 for your help here!

We can safely close this issue now thanks to your PR:
https://github.com/Homebrew/homebrew-core/pull/39797
