### ISSUE TITLE
when installed via brew, update check doesn't work but setup does

### ISSUE THREAD

**Issue by maplebed** [CircleCI-Public/circleci-cli#305]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?** feature request

**What is the current behavior?** 

When installed via brew, running `circleci update check` responds with 
```
➜  circleci update check
`update` is not available because this tool was installed using `homebrew`.
Please consult the package manager's documentation on how to update the CLI.
```

It refuses to say whether an upgrade is necessary or what to do to upgrade if one were available.

However, when running `circleci setup`, it happily both tells you that there is an update available and the specific command to run to get it:

```
➜  circleci setup
You are running 0.1.4786
A new release is available (0.1.5607)
You can update with `brew upgrade circleci`
```

It would be lovely if the command documented to tell you whether an upgrade was necessary had as useful output as the command that configures the CLI

**Which version of the CLI and OS are you using? Did this work in previous versions?**
running on OSX circleci version 0.1.4786, verified similar behavior in version 0.1.5607

**Comment by marcomorain** [comment]
This is not a high priority issue for us at present, but we'd happily review a PR.

**Comment by corinnesollows** [comment]
@maplebed Closing this issue out, but please feel free to send us a PR if you choose to make these changes.
