### ISSUE TITLE
Improve setup command with instructions

### ISSUE THREAD

**Issue by maplebed** [CircleCI-Public/circleci-cli#306]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?** feature request

**What is the current behavior?**

When running `circleci setup` the first thing it does is ask you for an API token:

```
➜  circleci setup
✔ CircleCI API Token: 
```

This is lovely, and the obvious thing that's necessary.

In the output of `circleci diagnostic` when there is no token set up, it also gives you the handy URL you can load in order to create a token:

```
➜  circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/ben/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
Error: please set a token with 'circleci setup'
You can create a new personal API token here:
https://circleci.com/account/api
```

That is very useful! It would be nice if the step that asked you to provide a token also included the URL from which you can generate a token.

**Which version of the CLI and OS are you using? Did this work in previous versions?**
OSX, installed via homebrew, CLI version 0.1.5607

**Comment by rashansmith** [comment]
I would like to take this issue.

**Comment by corinnesollows** [comment]
@maplebed See issue #339 for further details, closing out.
