### ISSUE TITLE
circleci config validate is not working

### ISSUE THREAD

**Issue by adil26** [CircleCI-Public/circleci-cli#307]
Hi,

When I try to validate circleci config file then it throws following error:

Error: Could not load config file at .circleci/config.yml: open .circleci/config.yml: no such file or directory

Also when I setup circleci then it was setup in /home/pcname/.circleci/cli.yml but not in my current path.
So how can I solved it?

Thanks

**Comment by jkzilla** [comment]
Hello, you will receive this error if you are not in the root folder of the project that you are building. Please cd into the project folder and make sure there is a folder `.circleci` with a `config.yml` file. It must be named `config.yml`.
