### ISSUE TITLE
Support configurable settings location

### ISSUE THREAD

**Issue by christopher-dG** [CircleCI-Public/circleci-cli#311]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

A `~/.circleci` directory exists and I have no way to tell the CLI to use a different directory. I see there are some TODOs in the code so let this be a confirmation that "yes, this is wanted" :slightly_smiling_face:. I might work on it myself if I find the time.

Can you provide an example?

```
xps [ ~ ] rm -rf .circleci     
xps [ ~ ] circleci help   
Use CircleCI from the command line.

This project is the seed for CircleCI's new command-line application.

For more help, see the documentation here: https://circleci.com/docs/2.0/local-cli/


Usage:
  circleci [command]

Available Commands:
  config      Operate on build config files
  diagnostic  Check the status of your CircleCI CLI.
  help        Help about any command
  local       Debug jobs on the local machine
  namespace   Operate on namespaces
  orb         Operate on orbs
  query       Query the CircleCI GraphQL API.
  setup       Setup the CLI with your credentials
  update      Update the tool to the latest version
  version     Display version information

Flags:
  -h, --help           help for circleci
      --host string    URL to your CircleCI host, also CIRCLECI_CLI_HOST (default "https://circleci.com")
      --token string   your token for using CircleCI, also CIRCLECI_CLI_TOKEN
Use "circleci [command] --help" for more information about a command.
xps [ ~ ] ls .circleci
cli.yml  update_check.yml
```
**What is the expected behavior?**

Not expected but rather desired:  I can set an environment variable `CIRCLECI_HOME` or similar to tell the tool to use `$HOME/.config/circleci` instead.

**Which version of the CLI and OS are you using? Did this work in previous versions?**

`0.1.5691+a6d8251`, Arch Linux. No.

Please provide the output of `circleci version` and `circleci diagnostic`.

```
xps [ ~ ] circleci version   
0.1.5691+a6d8251
xps [ ~ ] circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /home/degraafc/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
Error: please set a token with 'circleci setup'
You can create a new personal API token here:
https://circleci.com/account/api
```

**If you have any questions, feel free to ping us at @CircleCI-Public/x-team.**

**Comment by weilbith** [comment]
I really like to see this happen. It pollutes the home directory.

**Comment by marcomorain** [comment]
I'd be happy to review a PR to add this support.

**Comment by corinnesollows** [comment]
@christopher-dG closing this out. Please feel free to send us a PR if you are still looking to make these changes.
