### ISSUE TITLE
[CIRCLE-14348] `circleci orb diff`

### ISSUE THREAD

**Issue by iynere** [CircleCI-Public/circleci-cli#312]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

lack of way to easily compare orb versions

Can you provide an example?

any orb

**What is the expected behavior?**

something like `circleci orb diff ORB-NAME SemVer1 SemVer2` that outputs code differences between orb versions

**Comment by royvandewater** [comment]
This sounds like it would be a great first issue for someone to grab. We already have the functionality for retrieving the source built in to the tool. In fact, we can kinda hack something like this together using diff:

```shell
#!/bin/bash

diff <(circleci orb source circleci/slack@3.3.0) <(circleci orb source circleci/slack@3.2.0)
```

**Comment by JulesFaucherre** [comment]
Hey @iynere , just letting you know that the feature has been added in [this pr](https://github.com/CircleCI-Public/circleci-cli/pull/815) and should be available if you update your CLI 😃
