### ISSUE TITLE
failed to start event processor: failed to compute task config: failed to read config file

### ISSUE THREAD

**Issue by kwuite** [CircleCI-Public/circleci-cli#316]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant. (none of the other missing config solutions worked for me)
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

Unable to locally execute circle ci for testing my builds.

Can you provide an example?

```
git clone https://github.com/CircleCI-Public/circleci-demo-go.git
cd circleci-demo-go
circleci local execute --job build
```

Result

```
Docker image digest: sha256:463f8b03fa34e7609792bbc3e8983167fbb1221d9cefb1be401c0952973b3ebb
Error: failed to start event processor: failed to compute task config: failed to read config file: open circle.yml: no such file or directory
```

Config is valid

```
~/circleci-demo-go$ circleci config validate
Config file at .circleci/config.yml is valid.
```

Both docker and circleci are running within my user space without the need of sudo.

**What is the expected behavior?**

When I run the example code from "https://circleci.com/docs/2.0/local-cli/" I expect the config file to be found and that it runs the job.

**Which version of the CLI and OS are you using? Did this work in previous versions?**

Never used a previous version.

- Windows 10 Pro 1903, build 18363.264
- WSL: Linux MSI 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
- Ubuntu 18.04
- 32g ram, 64bit, core i7-8750h
- Docker version 18.09.6, build 481bc77

Please provide the output of `circleci version` and `circleci diagnostic`.

`0.1.5725+b0a23c0`

and

```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /home/wemeet/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Kelvin.
```

Related to: #290

**Comment by kwuite** [comment]
Installed the cli with: `curl -fLSs https://circle.ci/cli | sudo bash`

**Comment by john-mcgowan-wowza** [comment]
@kwuite Unfortunately I haven't worked with the windows side of things in months.

But I think the issue I had was resolved by fixing up some SSH authentication stuff... But I'm not 100% sure.  Sorry I can't be more helpful for you right now.

**Comment by kwuite** [comment]
@john-mcgowan-wowza , are you suggesting the cli tool is pulling from git at startup? 

Maybe it is trying to connect to some libraries to setup the docker environment. I guess it is time to read the source code then....

Anyways, thanks for replying and in case something pops up I gladly here your thoughts.

**Comment by royvandewater** [comment]
Hi @kwuite! Would it be possible to try running this on the latest version of WSL? I don't have a windows machine on hand to test, but from the description, it sounds like they included some functionality that specifically targets enabling Docker filesystem interaction. 

https://docs.microsoft.com/en-us/windows/wsl/wsl2-about

**Comment by kwuite** [comment]
@royvandewater ,

Tried a few times but have not been able to get wsl2 even when im on the windows insider program. Will follow up once I get some more time for this.

**Comment by kwuite** [comment]
Tried following this guide: https://docs.microsoft.com/en-us/windows/wsl/wsl2-install I had already joined the windows insider program (early this year) but I am unable to get the upgrade to build version 18917. As long as that is not possible for my machine I will not be able to test WSL2.

**Comment by kwuite** [comment]
I can confirm CircleCI works with WSL2 and will not work with WSL because of the way the docker architecture works.
