### ISSUE TITLE
update_test test cases failing locally

### ISSUE THREAD

**Issue by mvxt** [CircleCI-Public/circleci-cli#317]
- [X] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [X] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**
Report a bug / ask a question

**What is the current behavior?**
Running `make test` locally fails 4 test cases in `/cmd/update_test.go`.

**Can you provide an example?**
All four test cases are failing with the same error: rather than getting "You are running 0.0.0-dev" I get the message "No updates found."

```
------------------------------
• Failure [0.049 seconds]
Update
/Users/mvxt_cci/workspace/circleci-cli/cmd/update_test.go:17
  update --check
  /Users/mvxt_cci/workspace/circleci-cli/cmd/update_test.go:59
    with flag should tell the user how to update and install [It]
    /Users/mvxt_cci/workspace/circleci-cli/cmd/update_test.go:67

    No future change is possible.  Bailing out early after 0.046s.
    Got stuck at:
        No updates found.

    Waiting for:
        You are running 0.0.0-dev

    /Users/mvxt_cci/workspace/circleci-cli/cmd/update_test.go:73
------------------------------
```

**What is the expected behavior?**
Should say "You are running 0.0.0-dev" but it says there are no more updates.

**Which version of the CLI and OS are you using? Did this work in previous versions?**
Occurs on latest `master` commit. Using macOS Mojave 10.14.5. Not sure if this worked in previous version because I've only cloned this repo within the last week or two.

**Please provide the output of `circleci version` and `circleci diagnostic`.**
The following output is after compiling the executable and running that rather than installing from package manager like brew.
```
[13:21:03] mvxt_cci:circleci-cli git:(master*) $ ./circleci-cli version
0.0.0-dev
[13:21:04] mvxt_cci:circleci-cli git:(master*) $ ./circleci-cli diagnostic
You are running 0.0.0-dev
A new release is available (0.1.5725)
You can visit the Github releases page for the CLI to manually download and install:
https://github.com/CircleCI-Public/circleci-cli/releases


---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/mvxt_cci/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Michael Thanh.
[13:21:09] mvxt_cci:circleci-cli git:(master*) $
```

So it looks like if I run the compiled executable, the "version" is correct and prints out the correct message. But for some reason the test fails. I'm still fairly new to Go and don't know how to debug this yet.

**Additional Info**
I do not have the CircleCI CLI installed from any other sources:
```
[13:26:34] mvxt_cci:circleci-cli git:(master*) $ which circleci
circleci not found
[13:26:37] mvxt_cci:circleci-cli git:(master*) $ which circleci-cli
circleci-cli not found
[13:26:39] mvxt_cci:circleci-cli git:(master*) $
```

**Comment by marcomorain** [comment]
I fixed this a couple of weeks ago. The problem was that the tests only worked on Linux, and they now support macOS.
