### ISSUE TITLE
circleci build should read config from stdin

### ISSUE THREAD

**Issue by nikolaik** [CircleCI-Public/circleci-cli#343]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I am able to validate a config file piped in to the process stdin using `-` as config path, but not when trying to run a build.

Here is an example:
```console
$ circleci config process .circleci/config.yml | circleci config validate -c -
Config input is valid.
$ circleci config process .circleci/config.yml | circleci build -c -
Error: Unable to read config file: open -: no such file or directory
```
**What is the expected behavior?**
The `circleci build` config param `-c` set to `-` is interpreted as *read config from stdin*. Meaning I am able to run a build when piping in a config file to the process stdin using `-` as config path.
```console
$ circleci config process .circleci/config.yml | circleci build -c -
<build starts and output from it follows>
```

**Comment by marcomorain** [comment]
Hi @nikolaik  - we've added config version 2.1 support to local builds now, which I think you were trying to achieve here, right? Please us know if the 2.1 support doesn't solve this for you. Thanks.

**Comment by nikolaik** [comment]
> Hi @nikolaik - we've added config version 2.1 support to local builds now, which I think you were trying to achieve here, right? 

You are right, thank you ✨
