### ISSUE TITLE
CLI should accept 2.1 configs and support 2.1 features

### ISSUE THREAD

**Issue by robin900** [CircleCI-Public/circleci-cli#347]
- [x ] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x ] I have checked for similar issues and haven't found anything relevant.
- [x ] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**

At first I thought "bug", but perhaps this is really a feature request.

**What is the current behavior?**

CLI considers config version `2.1` to be an invalid version. Try `circleci local execute --job somejob` for a `config.yml` file that has `version: 2.1` at the top. You will see the following output:

```
Error:
You attempted to run a local build with version '2.1' of configuration.
Local builds do not support that version at this time.
```

**What is the expected behavior?**

If I use a locally-built CLI with `build.go` changed to consider `2.1` a valid version string, the CLI accepts the config and attempts the requested operation (`local execute`, in my case).

**Which version of the CLI and OS are you using? Did this work in previous versions?**

0.1.5879+416032d
MacOS 10.14.6 (Mojave)
didn't try with previous versions (first installation of tool)

Please provide the output of `circleci version` and `circleci diagnostic`.

```
±  |master U:3 ?:1 ✗| → circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/avvir/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Robin.

±  |master U:3 ?:1 ✗| → circleci version
0.1.5879+416032d
```

**If you have any questions, feel free to ping us at @CircleCI-Public/x-team.**

**Comment by marcomorain** [comment]
Hi @robin900, this has shipped this week 🎉 

Can you give it a go and let us know if you have any problems please?

**Comment by robin900** [comment]
@marcomorain I've updated the tool, and run `circleci config validate` and `circleci config process` on a 2.1 version config file. The tool properly processes the version 2.1 config into a version 2.0 config, applying the referenced orbs correctly. Thanks!

**Comment by marcomorain** [comment]
Awesome!
