### ISSUE TITLE
Unexpected exception processing config

### ISSUE THREAD

**Issue by michael-browne** [CircleCI-Public/circleci-cli#353]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
When trying to validate any config file the following error occurs:

```
Error: Unexpected exception processing config
Please contact support
```

Can you provide an example?

Contents of `.circleci/config.yml`:
```
version: 2
```

Result of validation:
```
$ circleci config validate
Error: Unexpected exception processing config
Please contact support
```

With debug flag:
```
circleci --debug config validate
>> variables: map[config:version: 2
]
>> query:
		query ValidateConfig ($config: String!) {
			buildConfig(configYaml: $config) {
				valid,
				errors { message },
				sourceYaml,
				outputYaml
			}
		}
<< request id: ef5dbc7b-0490-4a62-8baa-c62b16863700
<< result status: 200 OK
<< {"data":{"buildConfig":{"valid":false,"errors":[{"message":"Unexpected exception processing config"},{"message":"Please contact support"}],"sourceYaml":"version: 2\n","outputYaml":"jobs:\n  Build Error:\n    docker:\n    - image: bash:4.4.19\n    steps:\n    - run:\n        name: Config Processing Error (Don't rerun)\n        command: \"# Unexpected exception processing config\\n# Please contact support\\n\\\n          # \\n# -------\\n# Warning: This configuration was auto-generated to show\\\n          \\ you the message above.\\n# Don't rerun this job. Rerunning will have no\\\n          \\ effect.\\nfalse\"\nworkflows:\n  version: 2\n  Build Error:\n    jobs:\n    - Build Error\nversion: 2\n\n# Original config.yml file:\n# version: 2"}}}
Error: Unexpected exception processing config
Please contact support
```

**What is the expected behavior?**

I expect the file to be validated without an exception occuring.

**Which version of the CLI and OS are you using? Did this work in previous versions?**

```
$ circleci version
0.1.5879+416032d
```

```
$ circleci diagnostic
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/<home directory>/.circleci/cli.yml
API host: https://circleci.<domain>.com/
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, michael.browne.
```
(I've removed any sensitive info, the domain and config directory are set correctly)

I'm running macOS Mojave 10.14.6

I've tried installing CircleCI CLI directly and through homebrew, but get the same results either way.

I haven't tried any previous versions on CircleCI CLI

**If you have any questions, feel free to ping us at @CircleCI-Public/x-team.**

**Comment by michael-browne** [comment]
This appears to have been a problem with my company's local deployment of CircleCI, it works fine if I use circleci.com so I'll close this issue.

**Comment by cthayer** [comment]
@michael-browne can you share what the issue was with your company's local deployment of CircleCI?

I'm having the same problem using my company's internal deployment of CircleCI.

**Comment by michael-browne** [comment]
@cthayer 
I'm afraid I never did find out what the cause of the problem was.
