### ISSUE TITLE
No contribution guidelines for documentation PRs

### ISSUE THREAD

**Issue by buzzedword** [CircleCI-Public/circleci-cli#354]
- [X] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**
Neither
**What is the current behavior?**
n/a
**Can you provide an example?**
n/a
**What is the expected behavior?**
n/a
**Which version of the CLI and OS are you using? Did this work in previous versions?**
n/a
Please provide the output of `circleci version` and `circleci diagnostic`.
n/a
**If you have any questions, feel free to ping us at @CircleCI-Public/x-team.**

I'd like to start documenting the process in which the circleci-cli can be used in a WSL2 windows environment. In order to properly document these steps, the contribution guidelines do not outline best practices for documentation or style guides.

Please advise the best way to open a documentation based PR with this project.

**Comment by marcomorain** [comment]
Hi @buzzedword - thanks for opening the issue. I think that the best place for this type of documentation is in [our docs repo](https://github.com/circleci/circleci-docs/blob/master/CONTRIBUTING.md#contributing-to-circleci-docs). If you visit the [docs page for the CLI](https://circleci.com/docs/2.0/local-cli/#section=configuration), you can open a GH issue using the links at the bottom of the page.
