### ISSUE TITLE
Running circleci build command fails with error

### ISSUE THREAD

**Issue by packtci** [CircleCI-Public/circleci-cli#37]
System Configuration Information:

Macbook Pro Laptop Mid 2015
Macos High Sierra Version 10.13.5

CircleCI CLI Version:

<img width="617" alt="screen shot 2018-07-28 at 6 28 23 pm" src="https://user-images.githubusercontent.com/40322425/43361079-0ab5205a-9294-11e8-907e-a5ba71758f76.png">

Docker Version:
<img width="460" alt="screen shot 2018-07-28 at 6 25 52 pm" src="https://user-images.githubusercontent.com/40322425/43361069-bd5ac65c-9293-11e8-98f5-7f6ad4fddb51.png">

I am running the command:

`circleci build` and getting these errors in the terminal:

<img width="1322" alt="screen shot 2018-07-28 at 6 27 17 pm" src="https://user-images.githubusercontent.com/40322425/43361074-ea7977dc-9293-11e8-871d-c737539fc275.png">

Note I got this same error with this version of the local cli that is in the circle ci docs:

$ curl -o /usr/local/bin/circleci https://circle-downloads.s3.amazonaws.com/releases/build_agent_wrapper/circleci && chmod +x /usr/local/bin/circleci

I tried this with the following docker images:

* circleci/golang:1.9
* circleci/node:7.10

**Comment by dnephin** [comment]
Thanks for the bug report! The root cause of the error is that a temporary directory could not be created. You can try setting another path for root of the temporary directory by using the `TMPDIR` environment variable.

**Comment by dnephin** [comment]
The panic was fixed in another repo.

**Comment by jbelmont** [comment]
Okay thanks @dnephin
