### ISSUE TITLE
Storing secrets on a context with the CLI is not possible due to "List" permissions

### ISSUE THREAD

**Issue by srbry** [CircleCI-Public/circleci-cli#379]
- [ ] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [ ] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Can you provide an example?

```
circleci context store-secret github <my_org> <my_context> <secret_name>
```

```
Error: failed to load context list: Non-nullable field was null.
Must have admin permission.
```

I would guess this is an issue with the API permissions rather than the CLI code but not sure where else to raise it.

I have permissions in the circleci ui to list, create, delete contexts etc, however, listing contexts with the CLI gives the above error requiring "admin permission".

Strangely the CLI does let me create a context, that I am then unable to view or store secrets in as show, list and store-secret all call the API for list contexts that returns a permission error.

**What is the expected behavior?**

Store a secret in a context without issue

**Which version of the CLI and OS are you using? Did this work in previous versions?**

Please provide the output of `circleci version` and `circleci diagnostic`.

```
~ $ circleci version
0.1.6494+9ebc42b
~ $ circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/sam/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
```

**If you have any questions, feel free to ping us at @CircleCI-Public/x-team.**

**Comment by srbry** [comment]
A little more info. If you manually get the context ID then permissions work for getting a single context, adding/ deleting contexts and creating and deleting secrets within the context. So it must be something specific the list contexts graphql

**Comment by marcomorain** [comment]
Thanks for the heads up @srbry , and thanks for the extra info, this really helps – we'll investigate this tomorrow.

**Comment by marcomorain** [comment]
Hi @srbry – my team are currently re-writing a chunk of this API internally, we are going to address this over the coming weeks as that work is deployed. I'll keep this ticket updated as we roll our changes out.

**Comment by aengelberg** [comment]
This has been fixed in the latest version.
