### ISSUE TITLE
"Error in the HTTP2 framing layer" when installing

### ISSUE THREAD

**Issue by Pi-George** [CircleCI-Public/circleci-cli#382]
$ curl -fLSs https://circle.ci/cli | bash
curl: (16) Error in the HTTP2 framing layer

Also if I install with snap I have no way to downgrade to a lower version or choose a version.

**Comment by Pi-George** [comment]
```
#!/bin/bash# If circleci command isn't found
if ! which circleci &>/dev/null; then
    wget -c https://github.com/CircleCI-Public/circleci-cli/releases/download/v0.1.5879/circleci-cli_0.1.5879_linux_amd64.tar.gz -O - | tar -xz
    sudo mv circleci-cli_0.1.5879_linux_amd64/circleci /usr/bin/
    echo "CircleCi executable moved to /usr/bin/circleci, to uninstall just delete the file"
    rm -rf circleci-cli_0.1.5879_linux_amd64
else
    echo "CircleCi Local is already installed at $(which circleci). Delete the file and run this script again to re-install"
fi
```

Workaround

**Comment by aengelberg** [comment]
This seems to be an issue with HTTP 2 redirecting to HTTP 1.1, which cURL can't handle until a later version. Some more potential workarounds I've discovered as I dug into this:

* Add `--http1.1` to the curl command
* Upgrade curl to a later version than what's in your package manager (not easy)

To avoid needing to worry about any of this, I've updated our README instructions to not involve the `circle.ci/cli` URL; they just hit the GitHub resource directly.
