### ISSUE TITLE
[GraphQL]: `orb publish` returns "Non-nullable field was null" if it doesn't exist

### ISSUE THREAD

**Issue by Dominik-K** [CircleCI-Public/circleci-cli#427]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`circleci orb publish orb.yml NAMESPACE/ORB_NOT_EXISTENT@dev:test` returns 
> Error: Non-nullable field was null.

**What is the expected behavior?**
It returns an error-message clearly indicating that this orb name doesn't exist.

**Which version of the CLI and OS are you using? Did this work in previous versions?**
Tested with [current `master`](https://github.com/CircleCI-Public/circleci-cli/commit/423e103f902f4fb689d7b1f7880636f41fc9551f).

**Comment by luispabon** [comment]
I'm hitting the same problem.

**Comment by luispabon** [comment]
The docs aren't very clear at all on this regard, and the error message could offer more help.

You need to be an admin, have a token and use the command line circleci tool to:

```
circleci orb create namespace/name
```

Would be great if the cli tool would volunteer this information, as well as being prominently displayed on the orb publishing help page.

**Comment by aengelberg** [comment]
This bug is now fixed. It was a backend fix, so no need to upgrade the CLI version.

**Comment by telfeky-plenty** [comment]
@aengelberg , I am facing same issue with "orb publish"

```

<< request id: 039f034f-dc53-4636-a81d-9ad84a9c7371
<< result status: 200 OK
<< {"data":null,"errors":[{"message":"Non-nullable field was null.","locations":[{"line":3,"column":4}],"path":["publishOrb"],"extensions":{"arguments":{"orbId":"$orbId","orbYaml":"$config","version":"$version"}}},{"message":"Something unexpected happened.","locations":[{"line":3,"column":4}],"path":["publishOrb"],"extensions":{"type":"INTERNAL","arguments":{"orbId":"$orbId","orbYaml":"$config","version":"$version"}}}]}
Error: Unable to publish orb: Non-nullable field was null.
Something unexpected happened.
```

how can i report backend issues , also how you identify root cause .?

**Comment by jackfarzan** [comment]
Having the same problem, a workflow that worked this morning is now not working due to the above reason.
