### ISSUE TITLE
Orb Tools link in readme points to the user's namespace

### ISSUE THREAD

**Issue by kbravh** [CircleCI-Public/circleci-cli#476]
## Meta:

**CircleCI CLI Version:** 0.1.10021+e267aba (release)

**Operating System:** Linux

---

## Current behavior:
When running the new command `circleci orb init` and scaffolding out a new project, the readme is auto-populated with the following link:
```md
A starter template for orb projects. Build, test, and publish orbs automatically on CircleCI with [Orb-Tools](https://circleci.com/orbs/registry/orb/kbravh/orb-tools).
```

## Expected behavior:
This should point to the CircleCI namespace for the actual orb-tools package.
```md
A starter template for orb projects. Build, test, and publish orbs automatically on CircleCI with [Orb-Tools](https://circleci.com/orbs/registry/orb/circleci/orb-tools).
```

**Comment by KyleTryon** [comment]
Thank you @kbravh, good find! Should be an easy fix for us.

**Comment by gmemstr** [comment]
https://github.com/CircleCI-Public/Orb-Project-Template/pull/7

**Comment by gmemstr** [comment]
This has been resolved in the new tag of the Orb Project Template :) https://github.com/CircleCI-Public/Orb-Project-Template/releases/tag/1.1.3 Since orb init will automatically pull the latest version there, is no further action needed.
