### ISSUE TITLE
orb publish returns "Non-nullable field was null"

### ISSUE THREAD

**Issue by juanimoli** [CircleCI-Public/circleci-cli#486]
## Meta:

**CircleCI CLI Version:**
```0.1.10656+c7c1710 (homebrew)```

**Operating System:**
macOS Catalina 10.15.7 (19H2)

**CircleCI CLI Diagnostic:**
```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/contingencia/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Juan Ignacio Molina.
```

---

## Current behavior:
Publishing an orb returns error even if re-installing or re doing the setup:
```
> circleci orb publish orb.yml org/orb@dev:test
Error: Unable to publish orb: Non-nullable field was null.
Something unexpected happened.
```
This should revive #427 

## Expected behavior:
Publish the orb

## When did this begin / Was this previously working?:
Since latest release? We don't know

**Comment by jackfarzan** [comment]
It was working at most 12 hours ago in our pipelines

**Comment by aengelberg** [comment]
Thanks for the report, we've addressed the backend issue causing this and orb publishing should be working again.
