### ISSUE TITLE
`circleci orb init` presents 'Error: open $(PATHNAME): is a directory'

### ISSUE THREAD

**Issue by seongwon-kang** [CircleCI-Public/circleci-cli#500]
## Meta:

**CircleCI CLI Version:**

0.1.11146+275feba (release)

**Operating System:**
Windows 10 Pro

**CircleCI CLI Diagnostic:**
```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: \cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...

```

---

## Current behavior:
Providing any not-existing path leads to `Error: open <path>: is a directory` error message

## Expected behavior:
Initial Setup processes

## When did this begin / Was this previously working?:
As I Installed `circleci-cli` on windows `choco`

**Comment by ThatCopy** [comment]
This bug is present from release v0.1.11113 onwards

**Comment by gmemstr** [comment]
Able to reliably replicate with the Windows binary. Assuming it's a Go bug - digging deeper shortly :+1:

**Comment by gmemstr** [comment]
This should be resolved as of #502! @ThatCopy @seongwon-kang Mind giving it a try?

**Comment by ThatCopy** [comment]
Yes, it's fixed now :+1:

**Comment by seongwon-kang** [comment]
It works in 0.1.11232 now.
