### ISSUE TITLE
Try to init with folder presents  `A context named orb-publishing already exists.` on Github setting stage

### ISSUE THREAD

**Issue by seongwon-kang** [CircleCI-Public/circleci-cli#503]
## Meta:

**CircleCI CLI Version:**
0.1.11232+94b7e37 (release)

**Operating System:**
Windows 10 Pro

**CircleCI CLI Diagnostic:**
```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: .circleci\cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
```

---

## Current behavior:

First, `cd` into folder which git local repo exists and tracks remote Github repo.

Try `circleci orb init .` to setup github repo that already exists
```
v Yes, set up a publishing context with my API key.
v Yes, set up the git project.
v Enter the remote git repository: https://github.com/<repo name that already exists>
Thank you! Setting up your orb...
Error: Non-nullable field was null.
A context named orb-publishing already exists.
```
Then try to `circleci orb init .` to setup github repo that not exists in remote
```
v Yes, set up the git project.
v Enter the remote git repository: https://github.com/<repo name that not exists in Github account>
Thank you! Setting up your orb...
Error: Non-nullable field was null.
A context named orb-publishing already exists.
```

## Expected behavior:

Ask if uses existing local/remote repo, or show error message for remove context and retry

## When did this begin / Was this previously working?:
As updated to version `0.1.11232+94b7e37 (release)`

**Comment by gmemstr** [comment]
Contexts are org/user level, so whether the repository exists or not doesn't really matter. Regardless, I think we can handle this better - digging into this deeper.

**Comment by gmemstr** [comment]
The error regarding an existing context will be handled as part of #506 :)
