### ISSUE TITLE
orb init fails with "repository already exists"

### ISSUE THREAD

**Issue by daniel-shuy** [CircleCI-Public/circleci-cli#514]
## Meta:

**CircleCI CLI Version:**

0.1.11417+edd023d

**Operating System:**

Windows

**CircleCI CLI Diagnostic:**

```
Debugger mode: false
Config found: C:\Users\Daniel Shuy\.circleci\cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Daniel Shuy.
```

---

## Current behavior:

Following the instructions at https://circleci.com/docs/2.0/orb-author/#getting-started, I created a Git repository, then ran `circleci orb init`, which fails at the `Would you like to set up your git project` step with `Error: repository already exists`.

I then pushed the project to Git, and set up the CircleCI pipeline, only for it to fail with `Cannot find daniel-shuy/renovate@dev:alpha in the orb registry. Check that the namespace, orb name and version are correct`.

Rerunning `circleci orb init` and skipping the `Would you like to set up your git project` step doesn't do anything either.

## Expected behavior:

`circleci orb init` should properly initialize the orb

## When did this begin / Was this previously working?:

Never worked for me

## Additional Information:

In the end I had to initialize the orb manually by doing:
1. Enable `Allow Uncertified Orbs` in `Organization Settings` -> `Security` -> `Orb Security Settings`
2. Run `circleci orb create daniel-shuy/renovate`
3. Run `circleci orb pack > orb.yml`
4. Run `circleci orb publish orb.yml daniel-shuy/renovate@dev:alpha`
5. Recreate default branch to retrigger build (build cannot be manually rerun because it is considered a Config Error)
6. Create `alpha` branch from default branch

I hope this helps anyone who runs into the same issue

**Comment by gmemstr** [comment]
Interesting - taking a look at this.

**Comment by gmemstr** [comment]
@daniel-shuy I'm having a tough time replicating this unfortunately - are you able to provide a screen capture or asciinema recording of the process that results in the error? Further, did you clone the repository locally, or did you allow the command to create the directory and `.git` directory?

**Comment by daniel-shuy** [comment]
Ah, I tried to simulate the issue again and I figured out what caused it. The first time I ran it, I faced a validation failure (eg. invalid orb name or something), which caused the directory to be partially initialized. Running it again with an empty directory solves it.
