### ISSUE TITLE
Feature Request: Select Category On Orb Creation

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/circleci-cli#522]
Orbs can now be categorized via the CLI to appear within search filters on the orb registry: https://circleci.com/docs/2.0/orb-author/#categorizing-your-orb

**Supported Categories:**

> 
> - Artifacts/Registry
> - Build
> - Cloud Platform
> - Code Analysis
> - Collaboration
> - Containers
> - Deployment
> - Infra Automation
> - Kubernetes
> - Language/Framework
> - Monitoring
> - Notifications
> - Reporting
> - Security
> - Testing

## Current behavior:
The orb init command will initiate a new orb

## Requested behavior:
Add a step to select a category for the orb on the registry.

**Comment by gmemstr** [comment]
@KyleTryon Any idea if we have an API endpoint that could potentially be used to keep this list up to date, rather than hardcoding?

**Comment by lokst** [comment]
@gmemstr Yes there is one, the circleci orb list-categories command uses it 🙂
