### ISSUE TITLE
circleci is not verified on macOS.

### ISSUE THREAD

**Issue by morpheism** [CircleCI-Public/circleci-cli#525]
## Meta:

**CircleCI CLI Version:**
v0.1.11508

**Operating System:**
macOS Catalina 10.15.7

**CircleCI CLI Diagnostic:**

---

## Current behavior:
`circleci` is not executable after installing manually. A macOS dialog pops up when executing from the Terminal:

> **“circleci” cannot be opened because the developer cannot be verified.**
macOS cannot verify that this app is free from malware.

## Expected behavior:
`circleci` should execute successfully.

## When did this begin / Was this previously working?:
After installation.

**Comment by abdelDriowya** [comment]
sorry for late response, but this should not happen If you install via brew.
I'll close the issue, since it was created 3 years ago, please reopen the issue if you still have this problem.
