### ISSUE TITLE
circleci orb init gives Error: "cannot call Ask() with a nil reference to record the answers"

### ISSUE THREAD

**Issue by hhtong** [CircleCI-Public/circleci-cli#526]
## Meta:

**CircleCI CLI Version:**
0.1.11508+10b61a8 (homebrew)

**Operating System:**
Mac 10.15.5

**CircleCI CLI Diagnostic:**
---
Debugger mode: false
Config found: /Users/htong/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
Hello, Heidi.

---
## Current behavior:
I'm following the [orb authoring process guide](https://circleci.com/docs/2.0/orb-author/#orb-development-kit). When I do the `circleci orb init` step, I end up with:

```
Thank you! Setting up your orb...
An initial commit has been created - please run 'git push origin master' to publish your first commit!
Error: cannot call Ask() with a nil reference to record the answers
```

## Expected behavior:
I should be able to initialize my orb without any errors.

## When did this begin / Was this previously working?:
I started trying out orbs this week. The automated setup has never worked for me.

## Additional Information:
I was looking through your source code and I noticed this line: https://github.com/CircleCI-Public/circleci-cli/blob/55a9ecc97284565cf9ebfd777f7dbe596e2706a2/cmd/orb.go#L1317

Then, when I tried to track the error that I got from `survey`, I found this: https://github.com/AlecAivazis/survey/blob/f45c05b5039ca1f9c9c562be232f1c4044e0add0/survey.go#L296-L299

Not sure if this is on the right track or not, but thought I'd point it out just in case. I'm new to orbs and could just be getting some step wrong.

**Comment by gmemstr** [comment]
@hhtong Thanks for raising - taking a look!
