### ISSUE TITLE
`circle orb init` takes the `--private` parameter, but will sometimes create a public orb instead

### ISSUE THREAD

**Issue by mikebryant** [CircleCI-Public/circleci-cli#601]
## Meta:

**CircleCI CLI Version:**

0.1.15338+850f9ac (homebrew)

**Operating System:**

Mac OSX

**CircleCI CLI Diagnostic:**

```

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/mikebryant/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Mike Bryant.
```

---

## Current behavior:

We ran `circleci orb init --private .`

The resulting orb was not private, and has led to the exposure of confidential information

## Expected behavior:

It should create a private orb, as documented

## Additional Information:

The `createOrb` command passes the parameter appropriately: https://github.com/CircleCI-Public/circleci-cli/blob/850f9acdbf24e4222bd4b36035e20c182e7db385/cmd/orb.go#L826
If you choose not to set up your git project, the call in initOrb hardcodes private to false: https://github.com/CircleCI-Public/circleci-cli/blob/850f9acdbf24e4222bd4b36035e20c182e7db385/cmd/orb.go#L1259

**Comment by gmemstr** [comment]
@mikebryant Seems some fixes were merged :) Would you mind updating your CLI and giving it another go?
