### ISSUE TITLE
Cannot publish orb, get "AUTHORIZATION_FAILURE" using same api key that let me create the organisation

### ISSUE THREAD

**Issue by insidewhy** [CircleCI-Public/circleci-cli#606]
## Meta:

**CircleCI CLI Version:**
0.1.15384+149d854 (release)

**Operating System:**
Linux (archlinux)

**CircleCI CLI Diagnostic:**
```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /home/james/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
```

## Current behavior:
```
% circleci &1 --debug orb publish orb.yml circletron/circletron@dev:first
>> variables: map[config:version: 2.1

description: >
  Conditionally execute and namespace jobs in a monorepo

executors:
  circletron-executor:
    docker:
      - image: circletron/circletron:0.0.2

jobs:
  trigger-jobs:
    executor: circletron-executor
    steps:
      - run:
          name: undo circleci branch mangling
          command: |
            if [ $(git rev-parse --abbrev-ref HEAD) != develop ]; then
              git branch -f develop origin/develop
            fi
      - run:
          name: trigger jobs
          command: circletron

workflows:
  trigger-jobs:
    jobs:
      - trigger-jobs
 namespaceName:circletron orbName:circletron version:dev:first]
>> query: 
		mutation($config: String!, $orbName: String, $namespaceName: String, $version: String!) {
			publishOrb(
				orbName: $orbName,
				namespaceName: $namespaceName,
				orbYaml: $config,
				version: $version
			) {
				orb {
					version
				}
				errors { message }
			}
		}
	
<< request id: d7c88079-ada5-4eba-a692-2d32d0590655
<< result status: 200 OK
<< {"data":{"publishOrb":{"orb":null,"errors":[{"message":"AUTHORIZATION_FAILURE"}]}}}
Error: AUTHORIZATION_FAILURE
```

No idea why `AUTHORIZATION_FAILURE` when I could use the same key to create the namespace and the orb.

I'm not sure if it's related but circleci seems kinda busted when it comes to my organisation, for example trying to go to "Organisation settings" followed by "Contexts" shows "Something Unexpected Happened".

https://app.circleci.com/settings/organization/github/circletron/contexts?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fcircletron%2Fcircletron

Same for the VCS organisation setting at https://app.circleci.com/settings/organization/github/circletron/vcs?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fcircletron%2Fcircletron

**Comment by insidewhy** [comment]
Ah had to "Refresh permissions".

**Comment by roberto-ebizmarts** [comment]
Hello.
Why is this closed?
@insidewhy what do you mean with: `Ah had to "Refresh permissions".`
Please, could you be more specific. What permissions should be refreshed? And where?

**Comment by insidewhy** [comment]
Yep it's hardly satisfying but you need to jump through some hoops. Life be like that. Circle can be buggy but mostly it's okay.
