### ISSUE TITLE
Configurable default duration for tests with missing timing data

### ISSUE THREAD

**Issue by matthiasS-da** [CircleCI-Public/circleci-cli#635]
## What problem does this feature solve?:

When splitting tests across parallel runs, Circleci provides the option of splitting tests by their duration. When the duration of a test is not known, circleci will assume the (hard-coded) default duration of 1 second.

Please make this default duration of 1 second configurable, so that longer values can be chosen.

## Provide an example:

Use case:
1. Start a test job that splits tests by timing data.
2. Cancel the test when the fast tests (duration up to 10 seconds) have terminated and the slow tests are still running.
3. This will upload incomplete timing data, covering the fast tests only.
4. Rerun the test job. This will download the timing data from 3. For the slow tests it will assume the default duration of 1 second. As a result, the tests will be split very unevenly, because all slow tests are assumed to be very fast.

If I could set the default duration to a higher value (say, 2 minutes), the test splitting would be much better.

**Comment by nbialostosky** [comment]
Hi @matthiasS-da  -- Thanks again for opening this issue.

I actually implemented this flag and have now documented it here:

https://github.com/circleci/circleci-docs/pull/5995

Let me know if you have any issues utilizing it!

**Comment by matthiasS-da** [comment]
Thanks! Highly appreciated.
