### ISSUE TITLE
Homebrew formula?

### ISSUE THREAD

**Issue by danielcompton** [CircleCI-Public/circleci-cli#64]
It'd be handy to be able to install this via Homebrew, if possible.

**Comment by zzak** [comment]
Hello @danielcompton!

I started to work on an update for homebrew just yesterday:
https://github.com/zzak/homebrew-core/tree/circleci-v0.1.1248

**Comment by zzak** [comment]
This should be fixed once Homebrew/homebrew-core#31311 is merged! :confetti_ball:
