### ISSUE TITLE
Circleci config process output is duplicated 

### ISSUE THREAD

**Issue by alex-verve** [CircleCI-Public/circleci-cli#642]
## Meta:

**CircleCI CLI Version:** v0.1.16225

**Operating System:**
Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64

**CircleCI CLI Diagnostic:**
[CI debug job run](https://app.circleci.com/pipelines/github/streetteam/root/140451/workflows/ee3666cf-294e-4322-aa6a-793d6088da94/jobs/1968362)

---

## Current behavior:

`circleci config process --pipeline-parameters '' .circleci/original_config.yml > .circleci/processed_config.yml` [is outputting processed config twice](https://app.circleci.com/pipelines/github/streetteam/root/140451/workflows/ee3666cf-294e-4322-aa6a-793d6088da94/jobs/1968362)

Causing following errors later
![image](https://user-images.githubusercontent.com/36153295/140735014-51cafe74-2c16-47fe-8047-c1255e4765ef.png)

```
# Unable to parse YAML
# while constructing a mapping
#  in 'string', line 1, column 1:
#     version: 2
#     ^
# found duplicate key version
#  in 'string', line 25301, column 1:
#     version: 2
#     ^
```

## Expected behavior:
No errors and no duplicated output for `circleci config process` command

## When did this begin?:
Just after `v0.1.16225` release

## Additional Information:

I had to [downgrade the CLI](https://app.circleci.com/pipelines/github/streetteam/root/140464/workflows/a64a3819-8041-466a-9186-99093da30fda/jobs/1968385) to `v0.1.16192` version to workaround this problem

**Comment by DavidS-cloud** [comment]
This seems to be caused by the duplication in https://github.com/CircleCI-Public/circleci-cli/pull/632/files#diff-c5694d4d0b3b030b84de1d8ea8af2a43dc7b8598525d50a734c100ac22b5fdaaR174-R175

**Comment by DavidS-cloud** [comment]
cc @aengelberg @kelvinkfli

**Comment by btielen** [comment]
I am also experiencing this issue on

CircleCI CLI Version: v0.1.16225

Operating System:
Operating System: Ubuntu 20.04.3 LTS
OSType: linux
Architecture: x86_64
