### ISSUE TITLE
`circleci orb init` creates repository with wrong branch

### ISSUE THREAD

**Issue by kieran-osgood** [CircleCI-Public/circleci-cli#646]
## Meta:

**CircleCI CLI Version:**
0.1.16225+8d5e389 (homebrew)

**Operating System:**
Mac OS Big Sur - 11.6 (20G165)

**CircleCI CLI Diagnostic:**
```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/kieranosgood/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Kieran Osgood.
```

---

## Current behavior:
When running the `circleci orb init` command at the point of selecting branch, I selected the default of main, and the output of the next steps where it says to push the branch correctly re-iterate main, but upon inspecting the branch it actually created the repository with it had used master, see:
![image](https://user-images.githubusercontent.com/17687552/141675253-06e0de7d-6091-4e5d-a072-5bbd25b76c35.png)

## Expected behavior:
Creates repository with the correct branch

## When did this begin / Was this previously working?:
Not sure, this is first time I've used the command and I only downloaded the cli today

**Comment by adamdmharvey** [comment]
Came here to report same issue.

For my git push, I had to just run,

```shell
git branch main
git push origin main
```

And it seemed to work, but agree that if I selected main, the locally initialized repo should have been init'd with the branch name I selected.
