### ISSUE TITLE
"https://httpbin.org/get?foo=bar"

### ISSUE THREAD

**Issue by Max521X** [CircleCI-Public/circleci-cli#754]
## Meta:

**CircleCI CLI Version:**

**Operating System:**

**CircleCI CLI Diagnostic:**

```
diag
```

---

**Comment by Max521X** [comment]
"https://httpbin.org/get?foo=bar"

**Comment by Max521X** [comment]
Can't connect Amazon Alexa.done all the required steps

**Comment by rlegan** [comment]
Hi

Sorry we didn't understood your issue.
Please provide us more details about your issue, feel free to re-open this issue afterwards and we will be glad to have a look.

Thanks!
