### ISSUE TITLE
Error: invalid character 'Y' looking for beginning of value

### ISSUE THREAD

**Issue by Maxim-Filimonov** [CircleCI-Public/circleci-cli#760]
## Meta:

**CircleCI CLI Version:**
Tried both:
- 0.1.20323+990c791 (release)
- 0.1.20239+571ae88 (homebrew)

**Operating System:**
Mac OS 12.4
**CircleCI CLI Diagnostic:**
```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/maxim/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.```
---
```

## Current behavior:

```
> circleci info org
Error: invalid character 'Y' looking for beginning of value
```

```
> circleci context list github conpagoaus
Error: invalid character 'Y' looking for beginning of value
```
## Expected behavior:
Working API calls to get the list of contexts and info about organisation

## When did this begin / Was this previously working?:
Not sure

## Additional information
Not sure if its specific issue connected to our org setup or a general issue with CLI.

**Comment by thanksyouall** [comment]
Help. Same error.

**Comment by Maxim-Filimonov** [comment]
> Help. Same error.

This error was caused by CircleCI flagging my account by mistake. Specifically [this section](https://support.circleci.com/hc/en-us/articles/360043679453-CircleCI-Terms-of-Service-Violation-Sanctioned-Country)

To check if your account has been flagged - try to push a commit that you expect a build to occur for. 
You will see an error like that in cirlec ci dashboard if that is the case:
<img width="645" alt="Screen Shot 2022-08-02 at 11 23 02 pm" src="https://user-images.githubusercontent.com/360645/182466445-51a3897a-e401-4e3b-87b8-24b692321616.png">
