### ISSUE TITLE
Publishing an orb with setup: true in the example, does not include setup: true

### ISSUE THREAD

**Issue by imlogang** [CircleCI-Public/circleci-cli#779]
## Meta:

**CircleCI CLI Version:**

**Operating System:**

**CircleCI CLI Diagnostic:**

---

## Current behavior:
When publishing an Orb with `setup: true` in an example on how to use a command, the example is published without `setup: true`.

## Expected behavior:
`setup: true` be included in the example.

## When did this begin / Was this previously working?:
First reported 9/15/22

**Comment by KyleTryon** [comment]
Setup is not included in the struct: https://github.com/CircleCI-Public/circleci-cli/blob/45afa93d0ae256aded8a2c3bbd3daae8adfa8842/cmd/orb.go#L954

**Comment by adamdmharvey** [comment]
@KyleTryon is adding setup to the struct the only change that might be needed? If so I'm happy to fire that, but not sure the steps necessary in the broader context of how do we get examples published to the orb catalog with `setup: true` included :)

**Comment by adamdmharvey** [comment]
Confirmed this now works! yay!

<img width="417" alt="image" src="https://github.com/CircleCI-Public/circleci-cli/assets/33203301/d54e992d-dd71-4163-9d79-dcb3cb58a56d">
