### ISSUE TITLE
Validate errors with Error: Configuration version 2.1 requires the "Enable Pipelines" project setting

### ISSUE THREAD

**Issue by jkzilla** [CircleCI-Public/circleci-cli#788]
## Meta:

**CircleCI CLI Version:**

0.1.20856+991bd2a
**Operating System:**

https://app.circleci.com/pipelines/github/jkzilla/cci-demo101b/3926/workflows/9b6b57ef-3216-4e86-82f7-93dd742e548a/jobs/7518 docker
**CircleCI CLI Diagnostic:**

```
diag
```

---

## Current behavior:

when running WITHIN a build in CCI validate throws error and fails with

```
circleci config validate

Error: Configuration version 2.1 requires the "Enable Pipelines" project setting. Enable pipelines under Project Settings -> Advanced Settings. In order to retrigger pipelines, you must push a new commit.
```

## Expected behavior:

doesnt throw error

## When did this begin / Was this previously working?:

1 year ago

**Comment by slayer321** [comment]
Hey @jkzilla .. is there any update on this issue.. Will you where able to fix it. I'm also seeing this error.

**Comment by JulesFaucherre** [comment]
Hello, you actually encountered a very confusing situation: the `circleci` CLI used in your job _**is not**_ the one in this repository. It is actually an internal CLI used for jobs specific purpose like allowing you to split your test runs and other features. This is the CLI that is provided for all the `cimg/` images!

To use the public CLI (the one presented in this repo), you should instead use the image `circleci/circleci-cli` for your job! Thanks for raising the issue though, we will add a notice in the internal CLI to warn people that this is maybe not the CLI they expect
