### ISSUE TITLE
Output breaks on narrow terminals

### ISSUE THREAD

**Issue by marcusirgens** [CircleCI-Public/circleci-cli#797]
## Meta:

**CircleCI CLI Version:**
```
0.1.22100+a77d125 (homebrew)
```

**Operating System:**
```
macOS 12.5.1 (21G83)
```

**CircleCI CLI Diagnostic:**

```
n/a
```

---

## Current behavior:
The output of the `circleci` command appears to be broken in my terminal whenever the window width is below 122 characters, due to the border effect that has been added:
<img width="1002" alt="Screenshot 2022-10-08 at 13 15 21" src="https://user-images.githubusercontent.com/8811904/194704850-03a594fe-1215-4eb9-abcd-f6cea6b18bdb.png">

## Expected behavior:
The border effect shouldn't break the output. There's only 1 line that "overflows" inside of the box area between 85 and 121 character output width (the `--host` help text). I would rather have that one line overflowing than _every single line on the screen_.

Possible solutions: 

- Don't draw this border at all.
- Disable the border if the window size is smaller than the bounding box size
- Allow me to disable the border

I don't want to spark a debate around "what is a reasonable window size", but I'm sure most developers don't always run their terminals in full-width or full-screen modes, and breaking output for aesthetic purposes seems like a tradeoff with more negative sides than positive ones? 

## When did this begin / Was this previously working?:
This seems to have been introduced in #782.

**Comment by adamdmharvey** [comment]
Whole heartedly agree with this one: the outline makes the CLI extremely ugly for me. (Have a MacBook Pro 15" with no external monitor, so not a massively large dev space so most of my console windows aren't full screen.)  I basically no longer use the `--help` locally; exclusively try to read the docs on the repo for how to use the CLI.

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/33203301/198370353-a63f6fad-856e-4b21-aa9e-de6302801c24.png">

**Comment by wyardley** [comment]
#862 didn't have "Fixes #797", so this didn't get closed, but should be resolved once #886 goes out and is released.

**Comment by elliotforbes** [comment]
Closing this as it should have gone live! Thanks again for the contribution @threepipes 🙌🏼
