### ISSUE TITLE
echo << pipeline.git.branch >> /home/circleci/parameters.json passes validate

### ISSUE THREAD

**Issue by jkzilla** [CircleCI-Public/circleci-cli#806]
## Meta:

0.1.22322+5ff92b4 (homebrew)

**Operating System:**
macos

## Current behavior:

ran validate on config, failed because 

                  echo << pipeline.git.branch >> /home/circleci/parameters.json
should be
                  echo << pipeline.git.branch >> >> /home/circleci/parameters.json

## Expected behavior:
fail if 
                  echo << pipeline.git.branch >> /home/circleci/parameters.json

**Comment by rlegan** [comment]
Hello,

Due to legal and technical reasons, we cannot add shellcheck validation.
You will have to manually check your commands or use shellcheck's website in order to validate your command.

Thank for the feedback !
