### ISSUE TITLE
orbs should be private by default

### ISSUE THREAD

**Issue by jsteinberg-rbi** [CircleCI-Public/circleci-cli#814]
Orbs should be private by default because if you don't read the documentation well enough, which is very possible, and don't happen to catch that an orb is public by default, then you're stuck with a bunk public orb, which may have a bunch of IP in it. Furthermore it's just a weird choice for the tool to publish as public by default and I would imagine creates unnecessary toil for cci support. Thanks!

**Comment by BeFunes** [comment]
@jsteinberg-rbi Thanks for the recommendation! 
We decided to address the problem in a slightly different way: https://github.com/CircleCI-Public/circleci-cli/pull/938
Now, if you don't specify whether an orb is public or private, you will be prompted to choose between the two. Hopefully you find that this solves your pain.
Closing this issue, but let us know if you have any more comments
