### ISSUE TITLE
Shellcheck breaks against cci parameter expansion syntax but dev kit fails RC009 also

### ISSUE THREAD

**Issue by jsteinberg-rbi** [CircleCI-Public/circleci-cli#819]
The orb dev kit has a bat for requiring include for any command > 64 chars, but shellcheck cannot handle cci parameter expansion syntax << >> and so to make this work you have to environment: ENV_VARS for all parameters in the command which makes using include and shellcheck pointless and is also a rank code smell. Is there a better solution? Is there a solution aside from excluding RC009 or setting all params to ENV_VARS?

**Comment by JulesFaucherre** [comment]
Hey, yes that is a limitation with shellcheck and there is no other solution that we know apart from the two you propose

**Comment by JulesFaucherre** [comment]
By the way don't hesitate to ask your question on the [orb-tools-orb repo](https://github.com/CircleCI-Public/orb-tools-orb)
