### ISSUE TITLE
Delivery Option: container.dev features

### ISSUE THREAD

**Issue by CodeMan99** [CircleCI-Public/circleci-cli#820]
# Devcontainer Features

I created a devcontainer feature that allows users of that ecosystem to install the circleci cli.

## References

* [features specification](https://containers.dev/implementors/features/) - documentation
* [features-starter](https://github.com/devcontainers/feature-starter) - a github.com template for creating new features and deploying them to _ghcr.io_.
* [devcontainer support](https://containers.dev/supporting) - list of editors and tools that support this specification.

## Question: Ownership

I currently have not published my implementation to the [features index](https://containers.dev/features).

Would the CircleCI-Public organization like to own & manage a feature for this purpose? If not, would it be acceptable for me to add my [circleci-cli](https://github.com/CodeMan99/features/tree/main/src/circleci-cli) implementation to the index?

**Comment by zbenhadi** [comment]
Hello @CodeMan99, sorry for the long response time. I see that you posted your feature to the features index of Devcontainer and we are thrilled !

Thank you for your contribution!
