### ISSUE TITLE
messy validation output

### ISSUE THREAD

**Issue by wyardley** [CircleCI-Public/circleci-cli#860]
## Meta:

**CircleCI CLI Version:**
```
0.1.23845+f59d90e (homebrew)
```

**Operating System:**
Mac OS X

**CircleCI CLI Diagnostic:**
```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/xx/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
Hello, xx.
```

## Current behavior:
```
% circleci config validate --org-slug github/joinforma    
Validating config with following values
	id:	00000000-0000-0000-0000-000000000001	number:	1	project.git_url:	https://github.com/xx/yyy	project.type:	github	git.tag:		git.branch:	foo/bar	git.revision:	b30ac0a34489c02db25b3d1a25cf4866f899fa45	git.base_revision:	b30ac0a34489c02db25b3d1a25cf4866f899fa45Config file at .circleci/config.yml is valid.
```

## Expected behavior:
This output should only be shown when a special flag is passed, _or_ there should be a config option to suppress it
It should also be formatted more nicely, and the validity statement at the end should be on a line by itself

## When did this begin / Was this previously working?:
Begin with the most recent update (post #855)

**Comment by particleflux** [comment]
Not only is it potentially undesired output, it _also_ generates potentially yaml on `circleci config process`, as the line does not start with a comment character. (and it is output to stdout, so a redirect to a file will pickup both the processed config _and_ the metadata output)

**Comment by wyardley** [comment]
@particleflux d'oh. yeah, I hadn't even looked at those subcommands or realized they were also printing this.

Hopefully someone from Circle will give some more context about whether this change is intentional and / or what the behavior should be.
In the meantime, I updated this to write to stdout.
