### ISSUE TITLE
Using the convenience install script to install CLI raises `cannot execute binary file: Exec format error` on aarch64

### ISSUE THREAD

**Issue by aristoHero** [CircleCI-Public/circleci-cli#866]
## Meta:

**Operating System:**

Linux aarch64

## Current behavior:

  After  installing  CircleCI CLI through the convenience script `curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | sudo bash`  I get  `cannot execute binary file: Exec format error`. I do this installation inside a circleci job step.

**Comment by JulesFaucherre** [comment]
Hey, we recently merged a [pr](https://github.com/CircleCI-Public/circleci-cli/pull/807) from @kelvintaywl which handles this! This will be released in the beginning of next week. FYI the repo's default branch is now `main` and not `master` so you should update the URL

Thanks for reporting this!
