### ISSUE TITLE
v0.1.24435 breaks validation of configs with private orbs. Again.

### ISSUE THREAD

**Issue by cdhunt** [CircleCI-Public/circleci-cli#871]
## Meta:

**CircleCI CLI Version:**
v0.1.24435

**Operating System:**
Build-agent version 1.0.164056-8943dc4a (2023-03-17T15:00:17+0000)
System information:
 Server Version: 20.10.18
 Storage Driver: overlay2
  Backing Filesystem: xfs
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Kernel Version: 5.15.0-1030-aws
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64

---

## Current behavior:
`$ circleci config validate -c .circleci/config.continue.yml -o github/MyOrg--token $CIRCLECI_TOKEN`

`config compilation contains errors: [{Cannot find namespace/private-orb@0.1 in the orb registry. Check that the namespace, orb name and version are correct.}]`

## Expected behavior:
CLI should find our private orbs.

## When did this begin / Was this previously working?:
It was working last week.

## Additional Information:
You broke the CLI the same way last year. You said you were going to add additional testing for private orbs.

* https://github.com/CircleCI-Public/circleci-cli/pull/792
* https://github.com/CircleCI-Public/circleci-cli/pull/793
* https://github.com/CircleCI-Public/circleci-cli/commit/5469dabd86fcfcf042175aa6e12a1a2f87d61c81

**Comment by elliotforbes** [comment]
Thanks for highlighting this to us promptly, as it stands, I'm unsure why the expanded test suite hasn't caught this issue before deployment and I'll be investigating why this is the case and how we can improve the test suite to prevent future regressions.
