### ISSUE TITLE
Error: Not Found when running circleci local execute

### ISSUE THREAD

**Issue by jrnail23** [CircleCI-Public/circleci-cli#888]
## Meta:

**CircleCI CLI Version:**
0.1.25007+8abc86a (homebrew)

**Operating System:**
Mac M1 macOS Monterey 12.6

**CircleCI CLI Diagnostic:**
```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/jamesnail/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, James Nail.
```

---

## Current behavior:
I'm trying to run a job locally, per [this tutorial](https://circleci.com/docs/how-to-use-the-circleci-local-cli/#running-a-job) ([code repo](https://github.com/CircleCI-Public/circleci-demo-go)), but when I run `circleci local execute build`, I get the following:
```
Error: Not Found
```
No other error info or output at all.

## Expected behavior:
I expected it to execute the job as indicated in the tutorial

## When did this begin / Was this previously working?:
N/A (never tried before)

## Additional Information:
This is also happening when trying to run a job on one of my actual work projects.  I resorted to the tutorial to confirm that I could run jobs locally at all, which of course failed.

CROSS POSTED at https://github.com/CircleCI-Public/circleci-demo-go/issues/20

**Comment by ivanvpan** [comment]
Same issue.
Version: 0.1.24783+93e3e61 (release)

**Comment by nshikov** [comment]
I got it working by installing an older version of circleci. This one that worked for me: v0.1.24435

You would have to use an alternative installation method from official docs:
https://circleci.com/docs/local-cli/#alternative-installation-method
but just download this `install.sh` file and update LATEST_URL in there to use tag instead of latest.

**Comment by ntindle** [comment]
This worked for me to set the version without having to modify the script 

`url -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | sudo VERSION="0.1.24435" bash`

**Comment by elliotforbes** [comment]
@jrnail23  - can I ask you to download the latest and try this out?

**Comment by elliotforbes** [comment]
I'm going to close this as I believe it's been resolved in the latest version of the CLI - if the problem persists then please let me know!
