### ISSUE TITLE
Documentation on Pack functionality

### ISSUE THREAD

**Issue by lswith** [CircleCI-Public/circleci-cli#89]
I see that there is a `circleci config pack <dir>` command but no documentation on how to use it or what it is for.

**Comment by zzak** [comment]
@lswith Thanks for your question!

`pack` is sort of reserved feature atm until we nail down the CD story for publishing orbs.

The idea is that you'd have a folder full of config, including sub folders for commands, jobs, maybe even other orbs -- and this command would collapse all of that into a single YAML file.

We'll be sure to update the documentation once that is fully fleshed out, for now stay tuned :bow:

**Comment by eric-hu** [comment]
Hi @lswith, I've added a [page about pack](https://github.com/CircleCI-Public/config-preview-sdk/blob/master/docs/packing-config-files-into-one.md) to config-preview-sdk repo. Does this provide the info you were looking for?

**Comment by lswith** [comment]
Yes! Much better. I was actually confused as to what an orb was since it
clashes with the ethereum orbs in google.

**Comment by eric-hu** [comment]
Interesting, I hadn't heard of that project before--looks cool :)

Thanks for confirming! Since it sounds like your original question was answered, I'll close this issue.
