### ISSUE TITLE
Readme Needs Development Instructions

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-cli#91]
We need development instructions for outside contributors and new CircleCI employees on how to config and build the CLI.

Can be in the readme, or if very verbose, it's own dev Markdown file.

**Comment by zzak** [comment]
That should be covered here:
https://github.com/CircleCI-Public/circleci-cli/blob/master/HACKING.md

**Comment by felicianotech** [comment]
How about the tiny PR I made ^ .
