### ISSUE TITLE
Set "maintainer" label for Docker image

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-cli#916]
The CLI Docker image is based of the Go Convenience Image. This means it inherits the labels from the upstream image, including the "maintainer" label which says that CPE is the maintainer of the image. It would be useful to add a new label for the team that owns the CLI.

---

I'm opening this issue because this situation happened which lead someone to the CPE team instead of DevExp.

**Comment by abdelDriowya** [comment]
ticket created for this, thanks for reporting
