### ISSUE TITLE
Json unmarshall error 

### ISSUE THREAD

**Issue by nathan454** [CircleCI-Public/circleci-cli#923]
## Meta:

**CircleCI CLI Version:**

0.1.26094+6f8e97e (homebrew)

**Operating System:**

  mac os

**CircleCI CLI Diagnostic:**

```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/nathan/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
```

---

## Current behavior:

  While running `circleci orb init PATH --private` 
  I chose `Yes, walk me through the process.`
  And in return I get an error `Error: Unexpected error: json: cannot unmarshal object into Go value of type []cmd.orbProtectTemplateRelease`

## Expected behavior:

Not have this json error
## When did this begin / Was this previously working?:

 First time trying this

**Comment by zbenhadi** [comment]
Hello @nathan454, thank you for your feedback, we will look into it and keep you up to date.

**Comment by abdelDriowya** [comment]
closing because no answer from OP.
please open the issue if you still have this issue.
