### ISSUE TITLE
Error: Unable to validate config

### ISSUE THREAD

**Issue by ValorHeart** [CircleCI-Public/circleci-cli#932]
## Meta:

**CircleCI CLI Version:**
0.1.26343+7b38e08 (homebrew)

**Operating System:**
MacOS Ventura 13.3.1

**CircleCI CLI Diagnostic:**
```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/***.***.circleci/cli.yml
API host: https://cci.riskxint.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
Hello, ***.
```

---

## Current behavior:
circleci orb validate orb.yml
Error: Unable to validate config: Exception applying arguments to field `orbConfig': Unknown argument `ownerId'.

## Expected behavior:
circleci orb validate orb.yml
No Error

## When did this begin / Was this previously working?:
Since latest CLI version

**Comment by JulesFaucherre** [comment]
Hey @ValorHeart , really sorry, when we added support for [org's private orb](https://github.com/CircleCI-Public/circleci-cli/pull/922) we did not handle backward compatibility
We're fixing it right now. Until it is fixed, you should be able to use version v0.1.26094 and above

**Comment by ValorHeart** [comment]
Thanks @JulesFaucherre , The new change about org's private orb is about your SAAS product and not hosted servers with private local orbs, right?

**Comment by JulesFaucherre** [comment]
Actually the change that was introduced allows `circleci orb validate` to validate private orbs that use private orbs, you will still be able to validate your hosted server private orbs, as long as they don't use other private orbs

**Comment by JulesFaucherre** [comment]
FYI the fix discussed is in [this pr](https://github.com/CircleCI-Public/circleci-cli/pull/934). The pr is now merged and will be released in the beginning of next week
