### ISSUE TITLE
Orb validation fails

### ISSUE THREAD

**Issue by the-fine** [CircleCI-Public/circleci-cli#992]
## Meta:

**CircleCI CLI Version:**

latest circleci/circleci-cli docker image

**Operating System:**

**CircleCI CLI Diagnostic:**

```
diag
```

---

## Current behavior:

running `circleci orb validate orb.yml` fails with ```Error:` Getting orb client: Cannot query field `_schema' on type ``QueryRoot'.```

## Expected behavior:

successfully validating the orb

## When did this begin / Was this previously working?:

looks like the release of this PR https://github.com/CircleCI-Public/circleci-cli/pull/968 caused this

**Comment by JulesFaucherre** [comment]
Sure, thanks for reporting! Are a Server customer?

**Comment by JulesFaucherre** [comment]
If yes, can you indicate you Server version?

**Comment by JulesFaucherre** [comment]
Alright, that was a very bad typo, we're releasing the fix very soon, thank you for reporting!

**Comment by JulesFaucherre** [comment]
Hey, the fix is deployed now, can you confirm the orb validation is working correctly? And if so close the issue

**Comment by the-fine** [comment]
Works now, thank you for the quick resolution!
